using System;
using System.Collections.Generic;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x0200034A RID: 842
	public class TradeAgreementLogEntry : LogEntry, IEncyclopediaLog
	{
		// Token: 0x060031F9 RID: 12793 RVA: 0x000CF95D File Offset: 0x000CDB5D
		internal static void AutoGeneratedStaticCollectObjectsTradeAgreementLogEntry(object o, List<object> collectedObjects)
		{
			((TradeAgreementLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060031FA RID: 12794 RVA: 0x000CF96B File Offset: 0x000CDB6B
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._kingdom1);
			collectedObjects.Add(this._kingdom2);
		}

		// Token: 0x060031FB RID: 12795 RVA: 0x000CF98C File Offset: 0x000CDB8C
		internal static object AutoGeneratedGetMemberValue_kingdom1(object o)
		{
			return ((TradeAgreementLogEntry)o)._kingdom1;
		}

		// Token: 0x060031FC RID: 12796 RVA: 0x000CF999 File Offset: 0x000CDB99
		internal static object AutoGeneratedGetMemberValue_kingdom2(object o)
		{
			return ((TradeAgreementLogEntry)o)._kingdom2;
		}

		// Token: 0x17000C07 RID: 3079
		// (get) Token: 0x060031FD RID: 12797 RVA: 0x000CF9A6 File Offset: 0x000CDBA6
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Years(4f);
			}
		}

		// Token: 0x060031FE RID: 12798 RVA: 0x000CF9B2 File Offset: 0x000CDBB2
		public TradeAgreementLogEntry(Kingdom kingdom1, Kingdom kingdom2)
		{
			this._kingdom1 = kingdom1;
			this._kingdom2 = kingdom2;
		}

		// Token: 0x060031FF RID: 12799 RVA: 0x000CF9C8 File Offset: 0x000CDBC8
		public override string ToString()
		{
			return this.GetEncyclopediaText().ToString();
		}

		// Token: 0x06003200 RID: 12800 RVA: 0x000CF9D5 File Offset: 0x000CDBD5
		public bool IsVisibleInEncyclopediaPageOf(MBObjectBase obj)
		{
			return obj == this._kingdom1 || obj == this._kingdom2;
		}

		// Token: 0x06003201 RID: 12801 RVA: 0x000CF9EB File Offset: 0x000CDBEB
		public TextObject GetEncyclopediaText()
		{
			TextObject textObject = new TextObject("{=1gDck6xi}{KINGDOM1_LINK} has signed a trade agreement with {KINGDOM2_LINK}.", null);
			textObject.SetTextVariable("KINGDOM1_LINK", this._kingdom1.EncyclopediaLinkWithName);
			textObject.SetTextVariable("KINGDOM2_LINK", this._kingdom2.EncyclopediaLinkWithName);
			return textObject;
		}

		// Token: 0x04000E58 RID: 3672
		[SaveableField(10)]
		private readonly Kingdom _kingdom1;

		// Token: 0x04000E59 RID: 3673
		[SaveableField(20)]
		private readonly Kingdom _kingdom2;
	}
}
