using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Information;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0
{
	// Token: 0x0200003D RID: 61
	public class PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM : Widget, IGeneratedGauntletMovieRoot
	{
		// Token: 0x06001048 RID: 4168 RVA: 0x00076EB5 File Offset: 0x000750B5
		public PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001049 RID: 4169 RVA: 0x00076EC0 File Offset: 0x000750C0
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new PropertyBasedTooltipWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new ListPanel(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new DimensionSyncWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_0_1 = new Widget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_1);
			this._widget_0_0_1_0 = new ListPanel(base.Context);
			this._widget_0_0_1.AddChild(this._widget_0_0_1_0);
			this._widget_0_0_2 = new DimensionSyncWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_2);
		}

		// Token: 0x0600104A RID: 4170 RVA: 0x00076FA0 File Offset: 0x000751A0
		public void SetIds()
		{
			this._widget_0.Id = "TooltipWidget";
			this._widget_0_0.Id = "Body";
			this._widget_0_0_1.Id = "PropertyListBackground";
			this._widget_0_0_1_0.Id = "PropertyList";
		}

		// Token: 0x0600104B RID: 4171 RVA: 0x00076FF0 File Offset: 0x000751F0
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			base.IsDisabled = true;
			this._widget_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.NeutralColor = new Color(0f, 0f, 0f, 0.8509805f);
			this._widget_0.AllyColor = new Color(0.02352941f, 0.09019608f, 0.01568628f, 0.8509805f);
			this._widget_0.EnemyColor = new Color(0.08627451f, 0.02745098f, 0.01960784f, 0.8509805f);
			this._widget_0.PropertyListBackground = this._widget_0_0_1;
			this._widget_0.PropertyList = this._widget_0_0_1_0;
			this._widget_0.EnemyTroopsTextBrush = base.Context.GetBrush("Tooltip.EnemyTroop.Text");
			this._widget_0.AllyTroopsTextBrush = base.Context.GetBrush("Tooltip.AllyTroop.Text");
			this._widget_0.NeutralTroopsTextBrush = base.Context.GetBrush("Tooltip.NeutralTroop.Text");
			this._widget_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_0_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.SuggestedWidth = 220f;
			this._widget_0_0_0.SuggestedHeight = 12f;
			this._widget_0_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_0.PositionYOffset = 5f;
			this._widget_0_0_0.DimensionToSync = DimensionSyncWidget.Dimensions.Horizontal;
			this._widget_0_0_0.IsEnabled = false;
			this._widget_0_0_0.PaddingAmount = 20;
			this._widget_0_0_0.WidgetToCopyHeightFrom = this._widget_0_0_1_0;
			this._widget_0_0_0.Sprite = base.Context.SpriteData.GetSprite("General\\TooltipHint\\tooltip_frame");
			this._widget_0_0_0.ExtendLeft = 4f;
			this._widget_0_0_0.ExtendRight = 4f;
			this._widget_0_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_1.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_0_1.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_0_0_1_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_1_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_0_1_0.MarginTop = 5f;
			this._widget_0_0_1_0.MarginBottom = 5f;
			this._widget_0_0_1_0.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_0_0_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_2.SuggestedHeight = 12f;
			this._widget_0_0_2.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_2.PositionYOffset = -5f;
			this._widget_0_0_2.Sprite = base.Context.SpriteData.GetSprite("General\\TooltipHint\\tooltip_frame");
			this._widget_0_0_2.ExtendLeft = 4f;
			this._widget_0_0_2.ExtendRight = 4f;
			this._widget_0_0_2.DimensionToSync = DimensionSyncWidget.Dimensions.Horizontal;
			this._widget_0_0_2.IsEnabled = false;
			this._widget_0_0_2.PaddingAmount = 20;
			this._widget_0_0_2.WidgetToCopyHeightFrom = this._widget_0_0_1_0;
		}

		// Token: 0x0600104C RID: 4172 RVA: 0x00077368 File Offset: 0x00075568
		public void RefreshBindingWithChildren()
		{
			PropertyBasedTooltipVM datasource_Root = this._datasource_Root;
			this.SetDataSource(null);
			this.SetDataSource(datasource_Root);
		}

		// Token: 0x0600104D RID: 4173 RVA: 0x0007738C File Offset: 0x0007558C
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				if (this._datasource_Root_TooltipPropertyList != null)
				{
					this._datasource_Root_TooltipPropertyList.ListChanged -= this.OnList_datasource_Root_TooltipPropertyListChanged;
					for (int i = this._widget_0_0_1_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0_1_0.GetChild(i);
						((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)this._widget_0_0_1_0.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_TooltipPropertyList = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x0600104E RID: 4174 RVA: 0x000775B6 File Offset: 0x000757B6
		public void SetDataSource(PropertyBasedTooltipVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x0600104F RID: 4175 RVA: 0x000775BF File Offset: 0x000757BF
		private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001050 RID: 4176 RVA: 0x000775C8 File Offset: 0x000757C8
		private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001051 RID: 4177 RVA: 0x000775D1 File Offset: 0x000757D1
		private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001052 RID: 4178 RVA: 0x000775DA File Offset: 0x000757DA
		private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001053 RID: 4179 RVA: 0x000775E3 File Offset: 0x000757E3
		private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001054 RID: 4180 RVA: 0x000775EC File Offset: 0x000757EC
		private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001055 RID: 4181 RVA: 0x000775F5 File Offset: 0x000757F5
		private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001056 RID: 4182 RVA: 0x000775FE File Offset: 0x000757FE
		private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001057 RID: 4183 RVA: 0x00077607 File Offset: 0x00075807
		private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001058 RID: 4184 RVA: 0x00077610 File Offset: 0x00075810
		private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsActive = this._widget_0.IsVisible;
				return;
			}
			if (propertyName == "Mode")
			{
				this._datasource_Root.Mode = this._widget_0.Mode;
				return;
			}
		}

		// Token: 0x06001059 RID: 4185 RVA: 0x00077665 File Offset: 0x00075865
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600105A RID: 4186 RVA: 0x00077673 File Offset: 0x00075873
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600105B RID: 4187 RVA: 0x00077682 File Offset: 0x00075882
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600105C RID: 4188 RVA: 0x00077691 File Offset: 0x00075891
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600105D RID: 4189 RVA: 0x000776A0 File Offset: 0x000758A0
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600105E RID: 4190 RVA: 0x000776AF File Offset: 0x000758AF
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600105F RID: 4191 RVA: 0x000776BE File Offset: 0x000758BE
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001060 RID: 4192 RVA: 0x000776CD File Offset: 0x000758CD
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001061 RID: 4193 RVA: 0x000776DC File Offset: 0x000758DC
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001062 RID: 4194 RVA: 0x000776EC File Offset: 0x000758EC
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "TooltipPropertyList")
			{
				this.RefreshDataSource_datasource_Root_TooltipPropertyList(this._datasource_Root.TooltipPropertyList);
				return;
			}
			if (propertyName == "IsActive")
			{
				this._widget_0.IsVisible = this._datasource_Root.IsActive;
				return;
			}
			if (propertyName == "Mode")
			{
				this._widget_0.Mode = this._datasource_Root.Mode;
				return;
			}
		}

		// Token: 0x06001063 RID: 4195 RVA: 0x00077760 File Offset: 0x00075960
		public void OnList_datasource_Root_TooltipPropertyListChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_0_0_1_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0_1_0.GetChild(i);
					((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0_1_0.GetChild(i);
					((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0_1_0.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_TooltipPropertyList.Count; j++)
				{
					TooltipProperty bindingObject = this._datasource_Root_TooltipPropertyList[j];
					this._widget_0_0_1_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate = new PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate);
				TooltipProperty tooltipProperty = this._datasource_Root_TooltipPropertyList[e.NewIndex];
				generatedWidgetData.Data = tooltipProperty;
				propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_0_1_0.AddChildAtIndex(propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate, e.NewIndex);
				propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.CreateWidgets();
				propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetIds();
				propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetAttributes();
				propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetDataSource(tooltipProperty);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_0_1_0.GetChild(e.NewIndex);
				((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_0_1_0.GetChild(e.NewIndex);
				((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_0_1_0.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06001064 RID: 4196 RVA: 0x000778FC File Offset: 0x00075AFC
		private void RefreshDataSource_datasource_Root(PropertyBasedTooltipVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				if (this._datasource_Root_TooltipPropertyList != null)
				{
					this._datasource_Root_TooltipPropertyList.ListChanged -= this.OnList_datasource_Root_TooltipPropertyListChanged;
					for (int i = this._widget_0_0_1_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0_1_0.GetChild(i);
						((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_0_1_0.GetChild(i);
						((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_0_1_0.RemoveChild(child2);
					}
					this._datasource_Root_TooltipPropertyList = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.IsVisible = this._datasource_Root.IsActive;
				this._widget_0.Mode = this._datasource_Root.Mode;
				this._widget_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0;
				this._datasource_Root_TooltipPropertyList = this._datasource_Root.TooltipPropertyList;
				if (this._datasource_Root_TooltipPropertyList != null)
				{
					this._datasource_Root_TooltipPropertyList.ListChanged += this.OnList_datasource_Root_TooltipPropertyListChanged;
					for (int j = 0; j < this._datasource_Root_TooltipPropertyList.Count; j++)
					{
						PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate = new PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate);
						TooltipProperty tooltipProperty = this._datasource_Root_TooltipPropertyList[j];
						generatedWidgetData.Data = tooltipProperty;
						propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_0_1_0.AddChildAtIndex(propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate, j);
						propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.CreateWidgets();
						propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetIds();
						propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetAttributes();
						propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetDataSource(tooltipProperty);
					}
				}
			}
		}

		// Token: 0x06001065 RID: 4197 RVA: 0x00077DBC File Offset: 0x00075FBC
		private void RefreshDataSource_datasource_Root_TooltipPropertyList(MBBindingList<TooltipProperty> newDataSource)
		{
			if (this._datasource_Root_TooltipPropertyList != null)
			{
				this._datasource_Root_TooltipPropertyList.ListChanged -= this.OnList_datasource_Root_TooltipPropertyListChanged;
				for (int i = this._widget_0_0_1_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0_1_0.GetChild(i);
					((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0_1_0.GetChild(i);
					((PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0_1_0.RemoveChild(child2);
				}
				this._datasource_Root_TooltipPropertyList = null;
			}
			this._datasource_Root_TooltipPropertyList = newDataSource;
			this._datasource_Root_TooltipPropertyList = this._datasource_Root.TooltipPropertyList;
			if (this._datasource_Root_TooltipPropertyList != null)
			{
				this._datasource_Root_TooltipPropertyList.ListChanged += this.OnList_datasource_Root_TooltipPropertyListChanged;
				for (int j = 0; j < this._datasource_Root_TooltipPropertyList.Count; j++)
				{
					PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate = new PropertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate);
					TooltipProperty tooltipProperty = this._datasource_Root_TooltipPropertyList[j];
					generatedWidgetData.Data = tooltipProperty;
					propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_0_1_0.AddChildAtIndex(propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate, j);
					propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.CreateWidgets();
					propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetIds();
					propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetAttributes();
					propertyBasedTooltip__TaleWorlds_Core_ViewModelCollection_Information_PropertyBasedTooltipVM_Dependency_1_ItemTemplate.SetDataSource(tooltipProperty);
				}
			}
		}

		// Token: 0x04000276 RID: 630
		private Widget _widget;

		// Token: 0x04000277 RID: 631
		private PropertyBasedTooltipWidget _widget_0;

		// Token: 0x04000278 RID: 632
		private ListPanel _widget_0_0;

		// Token: 0x04000279 RID: 633
		private DimensionSyncWidget _widget_0_0_0;

		// Token: 0x0400027A RID: 634
		private Widget _widget_0_0_1;

		// Token: 0x0400027B RID: 635
		private ListPanel _widget_0_0_1_0;

		// Token: 0x0400027C RID: 636
		private DimensionSyncWidget _widget_0_0_2;

		// Token: 0x0400027D RID: 637
		private PropertyBasedTooltipVM _datasource_Root;

		// Token: 0x0400027E RID: 638
		private MBBindingList<TooltipProperty> _datasource_Root_TooltipPropertyList;
	}
}
