using System;
using System.Collections.Generic;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.MapNotificationTypes
{
	// Token: 0x020002BE RID: 702
	public class AcceptCallToWarOfferMapNotification : InformationData
	{
		// Token: 0x0600255E RID: 9566 RVA: 0x0009D70A File Offset: 0x0009B90A
		internal static void AutoGeneratedStaticCollectObjectsAcceptCallToWarOfferMapNotification(object o, List<object> collectedObjects)
		{
			((AcceptCallToWarOfferMapNotification)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600255F RID: 9567 RVA: 0x0009D718 File Offset: 0x0009B918
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.OfferingKingdom);
			collectedObjects.Add(this.KingdomToCallToWarAgainst);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(this.TriggerTime, collectedObjects);
		}

		// Token: 0x06002560 RID: 9568 RVA: 0x0009D74A File Offset: 0x0009B94A
		internal static object AutoGeneratedGetMemberValueOfferingKingdom(object o)
		{
			return ((AcceptCallToWarOfferMapNotification)o).OfferingKingdom;
		}

		// Token: 0x06002561 RID: 9569 RVA: 0x0009D757 File Offset: 0x0009B957
		internal static object AutoGeneratedGetMemberValueKingdomToCallToWarAgainst(object o)
		{
			return ((AcceptCallToWarOfferMapNotification)o).KingdomToCallToWarAgainst;
		}

		// Token: 0x06002562 RID: 9570 RVA: 0x0009D764 File Offset: 0x0009B964
		internal static object AutoGeneratedGetMemberValueTriggerTime(object o)
		{
			return ((AcceptCallToWarOfferMapNotification)o).TriggerTime;
		}

		// Token: 0x17000962 RID: 2402
		// (get) Token: 0x06002563 RID: 9571 RVA: 0x0009D776 File Offset: 0x0009B976
		// (set) Token: 0x06002564 RID: 9572 RVA: 0x0009D77E File Offset: 0x0009B97E
		[SaveableProperty(1)]
		public Kingdom OfferingKingdom { get; private set; }

		// Token: 0x17000963 RID: 2403
		// (get) Token: 0x06002565 RID: 9573 RVA: 0x0009D787 File Offset: 0x0009B987
		// (set) Token: 0x06002566 RID: 9574 RVA: 0x0009D78F File Offset: 0x0009B98F
		[SaveableProperty(2)]
		public Kingdom KingdomToCallToWarAgainst { get; private set; }

		// Token: 0x17000964 RID: 2404
		// (get) Token: 0x06002567 RID: 9575 RVA: 0x0009D798 File Offset: 0x0009B998
		// (set) Token: 0x06002568 RID: 9576 RVA: 0x0009D7A0 File Offset: 0x0009B9A0
		[SaveableProperty(3)]
		public CampaignTime TriggerTime { get; private set; }

		// Token: 0x17000965 RID: 2405
		// (get) Token: 0x06002569 RID: 9577 RVA: 0x0009D7A9 File Offset: 0x0009B9A9
		public override TextObject TitleText
		{
			get
			{
				return new TextObject("{=ywL1bGlZ}Accept Call To War Offer", null);
			}
		}

		// Token: 0x17000966 RID: 2406
		// (get) Token: 0x0600256A RID: 9578 RVA: 0x0009D7B6 File Offset: 0x0009B9B6
		public override string SoundEventPath
		{
			get
			{
				return "event:/ui/notification/peace_offer";
			}
		}

		// Token: 0x0600256B RID: 9579 RVA: 0x0009D7BD File Offset: 0x0009B9BD
		public AcceptCallToWarOfferMapNotification(Kingdom offeringKingdom, Kingdom kingdomToCallToWarAgainst, TextObject descriptionText)
			: base(descriptionText)
		{
			this.OfferingKingdom = offeringKingdom;
			this.KingdomToCallToWarAgainst = kingdomToCallToWarAgainst;
			this.TriggerTime = CampaignTime.Now + Campaign.Current.Models.AllianceModel.DurationForOffers;
		}

		// Token: 0x0600256C RID: 9580 RVA: 0x0009D7F8 File Offset: 0x0009B9F8
		public AcceptCallToWarOfferMapNotification(TextObject description)
			: base(description)
		{
		}

		// Token: 0x0600256D RID: 9581 RVA: 0x0009D804 File Offset: 0x0009BA04
		public override bool IsValid()
		{
			return !this.TriggerTime.IsPast;
		}
	}
}
