using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.Core.ViewModelCollection.Selector;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000014 RID: 20
	public class CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_2_Standard_DropdownWithHorizontalControl__DependendPrefab : ListPanel
	{
		// Token: 0x060005FC RID: 1532 RVA: 0x0002DB7C File Offset: 0x0002BD7C
		public CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_2_Standard_DropdownWithHorizontalControl__DependendPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x060005FD RID: 1533 RVA: 0x0002DB88 File Offset: 0x0002BD88
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new ButtonWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_1 = new AnimatedDropdownWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_0_0 = new ButtonWidget(base.Context);
			this._widget_1_0.AddChild(this._widget_1_0_0);
			this._widget_1_0_0_0 = new ScrollingRichTextWidget(base.Context);
			this._widget_1_0_0.AddChild(this._widget_1_0_0_0);
			this._widget_1_0_0_1 = new HintWidget(base.Context);
			this._widget_1_0_0.AddChild(this._widget_1_0_0_1);
			this._widget_1_0_1 = new Widget(base.Context);
			this._widget_1_0.AddChild(this._widget_1_0_1);
			this._widget_1_0_1_0 = new HintWidget(base.Context);
			this._widget_1_0_1.AddChild(this._widget_1_0_1_0);
			this._widget_1_1 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
			this._widget_1_1_0 = new BrushWidget(base.Context);
			this._widget_1_1.AddChild(this._widget_1_1_0);
			this._widget_1_1_0_0 = new ScrollablePanel(base.Context);
			this._widget_1_1_0.AddChild(this._widget_1_1_0_0);
			this._widget_1_1_0_0_0 = new Widget(base.Context);
			this._widget_1_1_0_0.AddChild(this._widget_1_1_0_0_0);
			this._widget_1_1_0_0_0_0 = new ListPanel(base.Context);
			this._widget_1_1_0_0_0.AddChild(this._widget_1_1_0_0_0_0);
			this._widget_1_1_0_1 = new ScrollbarWidget(base.Context);
			this._widget_1_1_0.AddChild(this._widget_1_1_0_1);
			this._widget_1_1_0_1_0 = new Widget(base.Context);
			this._widget_1_1_0_1.AddChild(this._widget_1_1_0_1_0);
			this._widget_1_1_0_1_1 = new ImageWidget(base.Context);
			this._widget_1_1_0_1.AddChild(this._widget_1_1_0_1_1);
			this._widget_2 = new Widget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2_0 = new ButtonWidget(base.Context);
			this._widget_2.AddChild(this._widget_2_0);
		}

		// Token: 0x060005FE RID: 1534 RVA: 0x0002DE24 File Offset: 0x0002C024
		public void SetIds()
		{
			base.Id = "HorizontalControlParent";
			this._widget_1.Id = "DropdownParent";
			this._widget_1_0.Id = "DropdownButtonContainer";
			this._widget_1_0_0.Id = "DropdownButton";
			this._widget_1_0_0_0.Id = "SelectedTextWidget";
			this._widget_1_1.Id = "DropdownClipWidget";
			this._widget_1_1_0.Id = "DropdownContainerWidget";
			this._widget_1_1_0_0.Id = "ScrollablePanel";
			this._widget_1_1_0_0_0.Id = "ClipRect";
			this._widget_1_1_0_0_0_0.Id = "PrimaryUsageSelectorList";
			this._widget_1_1_0_1.Id = "VerticalScrollbar";
			this._widget_1_1_0_1_1.Id = "VerticalScrollbarHandle";
		}

		// Token: 0x060005FF RID: 1535 RVA: 0x0002DEEC File Offset: 0x0002C0EC
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.CoverChildren;
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0.SuggestedWidth = 40f;
			this._widget_0.SuggestedHeight = 43f;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.DoNotAcceptEvents = true;
			this._widget_0.IsVisible = true;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedWidth = 60f;
			this._widget_0_0.SuggestedHeight = 70f;
			this._widget_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0.Brush = base.Context.GetBrush("SPOptions.Dropdown.Left.Button");
			this._widget_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_1.SuggestedWidth = 303f;
			this._widget_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1.DropdownContainerWidget = this._widget_1_1_0;
			this._widget_1.ListPanel = this._widget_1_1_0_0_0_0;
			this._widget_1.Button = this._widget_1_0_0;
			this._widget_1.TextWidget = this._widget_1_0_0_0;
			this._widget_1.DropdownClipWidget = this._widget_1_1;
			this._widget_1.ScrollbarWidget = this._widget_1_1_0_1;
			this._widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_0.SuggestedHeight = 43f;
			this._widget_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_0.DoNotPassEventsToChildren = true;
			this._widget_1_0_0.Brush = base.Context.GetBrush("SPOptions.Dropdown.Center");
			this._widget_1_0_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_0_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1_0_0_0.MarginLeft = 7f;
			this._widget_1_0_0_0.MarginRight = 7f;
			this._widget_1_0_0_0.PositionYOffset = 1f;
			this._widget_1_0_0_0.Brush = base.Context.GetBrush("SPOptions.Dropdown.Center.Text");
			this._widget_1_0_0_0.IsAutoScrolling = false;
			this._widget_1_0_0_0.ScrollOnHoverWidget = this._widget_1_0_0;
			this._widget_1_0_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_1.ClipContents = true;
			this._widget_1_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_1_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_1_0.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_1_1_0.SuggestedWidth = 330f;
			this._widget_1_1_0.SuggestedHeight = 380f;
			this._widget_1_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_1_0.Brush = base.Context.GetBrush("SPOptions.Dropdown.Extension");
			this._widget_1_1_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_1_0_0.AutoHideScrollBars = true;
			this._widget_1_1_0_0.ClipRect = this._widget_1_1_0_0_0;
			this._widget_1_1_0_0.MarginBottom = 20f;
			this._widget_1_1_0_0.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_1_1_0_0.InnerPanel = this._widget_1_1_0_0_0_0;
			this._widget_1_1_0_0.VerticalScrollbar = this._widget_1_1_0_1;
			this._widget_1_1_0_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1_0_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_1_0_0_0.ClipContents = true;
			this._widget_1_1_0_0_0.MaxHeight = 348f;
			this._widget_1_1_0_0_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1_0_0_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_1_0_0_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_1_0_0_0_0.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_1_1_0_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_1_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1_0_1.SuggestedWidth = 8f;
			this._widget_1_1_0_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_1_1_0_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1_1_0_1.MarginTop = 8f;
			this._widget_1_1_0_1.MarginBottom = 18f;
			this._widget_1_1_0_1.MarginRight = 5f;
			this._widget_1_1_0_1.AlignmentAxis = AlignmentAxis.Vertical;
			this._widget_1_1_0_1.Handle = this._widget_1_1_0_1_1;
			this._widget_1_1_0_1.IsVisible = false;
			this._widget_1_1_0_1.MaxValue = 100f;
			this._widget_1_1_0_1.MinValue = 0f;
			this._widget_1_1_0_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_1_0_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1_0_1_0.SuggestedWidth = 4f;
			this._widget_1_1_0_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_1_0_1_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_1_1_0_1_0.AlphaFactor = 0.2f;
			this._widget_1_1_0_1_0.Color = new Color(0.3529412f, 0.2509804f, 0.2f, 1f);
			this._widget_1_1_0_1_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_1_0_1_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_1_0_1_1.SuggestedWidth = 8f;
			this._widget_1_1_0_1_1.SuggestedHeight = 10f;
			this._widget_1_1_0_1_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_1_0_1_1.Brush = base.Context.GetBrush("FaceGen.Scrollbar.Handle");
			this._widget_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2.SuggestedWidth = 40f;
			this._widget_2.SuggestedHeight = 43f;
			this._widget_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2.DoNotAcceptEvents = true;
			this._widget_2.IsVisible = true;
			this._widget_2_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_2_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2_0.SuggestedWidth = 60f;
			this._widget_2_0.SuggestedHeight = 70f;
			this._widget_2_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_2_0.Brush = base.Context.GetBrush("SPOptions.Dropdown.Right.Button");
		}

		// Token: 0x06000600 RID: 1536 RVA: 0x0002E5A8 File Offset: 0x0002C7A8
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_SelectionSelector != null)
				{
					this._datasource_Root_SelectionSelector.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectionSelector;
					this._widget_0_0.EventFire -= this.EventListenerOf_widget_0_0;
					this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
					this._widget_1.EventFire -= this.EventListenerOf_widget_1;
					this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
					this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
					this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
					this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
					this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
					this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
					this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
					this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
					this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
					this._widget_1_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0_1;
					this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
					this._widget_2_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0;
					if (this._datasource_Root_SelectionSelector_ItemList != null)
					{
						this._datasource_Root_SelectionSelector_ItemList.ListChanged -= this.OnList_datasource_Root_SelectionSelector_ItemListChanged;
						for (int i = this._widget_1_1_0_0_0_0.ChildCount - 1; i >= 0; i--)
						{
							Widget child = this._widget_1_1_0_0_0_0.GetChild(i);
							((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child).OnBeforeRemovedChild(child);
							((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)this._widget_1_1_0_0_0_0.GetChild(i)).DestroyDataSource();
						}
						this._datasource_Root_SelectionSelector_ItemList = null;
					}
					this._datasource_Root_SelectionSelector = null;
				}
				if (this._datasource_Root_Hint != null)
				{
					this._datasource_Root_Hint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
					this._widget_1_0_0_1.EventFire -= this.EventListenerOf_widget_1_0_0_1;
					this._widget_1_0_1_0.EventFire -= this.EventListenerOf_widget_1_0_1_0;
					this._datasource_Root_Hint = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000601 RID: 1537 RVA: 0x0002ED43 File Offset: 0x0002CF43
		public void SetDataSource(CampaignOptionItemVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06000602 RID: 1538 RVA: 0x0002ED4C File Offset: 0x0002CF4C
		private void EventListenerOf_widget_0_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root_SelectionSelector.ExecuteSelectPreviousItem();
			}
		}

		// Token: 0x06000603 RID: 1539 RVA: 0x0002ED66 File Offset: 0x0002CF66
		private void EventListenerOf_widget_1(Widget widget, string commandName, object[] args)
		{
			commandName == "OnDropdownClick";
		}

		// Token: 0x06000604 RID: 1540 RVA: 0x0002ED74 File Offset: 0x0002CF74
		private void EventListenerOf_widget_2_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root_SelectionSelector.ExecuteSelectNextItem();
			}
		}

		// Token: 0x06000605 RID: 1541 RVA: 0x0002ED8E File Offset: 0x0002CF8E
		private void EventListenerOf_widget_1_0_0_1(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_Hint.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_Hint.ExecuteEndHint();
			}
		}

		// Token: 0x06000606 RID: 1542 RVA: 0x0002EDC0 File Offset: 0x0002CFC0
		private void EventListenerOf_widget_1_0_1_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_Hint.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_Hint.ExecuteEndHint();
			}
		}

		// Token: 0x06000607 RID: 1543 RVA: 0x0002EDF2 File Offset: 0x0002CFF2
		private void PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06000608 RID: 1544 RVA: 0x0002EDFB File Offset: 0x0002CFFB
		private void boolPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06000609 RID: 1545 RVA: 0x0002EE04 File Offset: 0x0002D004
		private void floatPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600060A RID: 1546 RVA: 0x0002EE0D File Offset: 0x0002D00D
		private void Vec2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600060B RID: 1547 RVA: 0x0002EE16 File Offset: 0x0002D016
		private void Vector2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600060C RID: 1548 RVA: 0x0002EE1F File Offset: 0x0002D01F
		private void doublePropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600060D RID: 1549 RVA: 0x0002EE28 File Offset: 0x0002D028
		private void intPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600060E RID: 1550 RVA: 0x0002EE31 File Offset: 0x0002D031
		private void uintPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600060F RID: 1551 RVA: 0x0002EE3A File Offset: 0x0002D03A
		private void ColorPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06000610 RID: 1552 RVA: 0x0002EE43 File Offset: 0x0002D043
		private void HandleWidgetPropertyChangeOf_widget_0_0(string propertyName)
		{
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root_SelectionSelector.IsEnabled = this._widget_0_0.IsEnabled;
				return;
			}
		}

		// Token: 0x06000611 RID: 1553 RVA: 0x0002EE69 File Offset: 0x0002D069
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000612 RID: 1554 RVA: 0x0002EE72 File Offset: 0x0002D072
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000613 RID: 1555 RVA: 0x0002EE7B File Offset: 0x0002D07B
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000614 RID: 1556 RVA: 0x0002EE84 File Offset: 0x0002D084
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000615 RID: 1557 RVA: 0x0002EE8D File Offset: 0x0002D08D
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000616 RID: 1558 RVA: 0x0002EE96 File Offset: 0x0002D096
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000617 RID: 1559 RVA: 0x0002EE9F File Offset: 0x0002D09F
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000618 RID: 1560 RVA: 0x0002EEA8 File Offset: 0x0002D0A8
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000619 RID: 1561 RVA: 0x0002EEB1 File Offset: 0x0002D0B1
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x0600061A RID: 1562 RVA: 0x0002EEBA File Offset: 0x0002D0BA
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "CurrentSelectedIndex")
			{
				this._datasource_Root_SelectionSelector.SelectedIndex = this._widget_1.CurrentSelectedIndex;
				return;
			}
		}

		// Token: 0x0600061B RID: 1563 RVA: 0x0002EEE0 File Offset: 0x0002D0E0
		private void PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x0600061C RID: 1564 RVA: 0x0002EEE9 File Offset: 0x0002D0E9
		private void boolPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x0600061D RID: 1565 RVA: 0x0002EEF2 File Offset: 0x0002D0F2
		private void floatPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x0600061E RID: 1566 RVA: 0x0002EEFB File Offset: 0x0002D0FB
		private void Vec2PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x0600061F RID: 1567 RVA: 0x0002EF04 File Offset: 0x0002D104
		private void Vector2PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x06000620 RID: 1568 RVA: 0x0002EF0D File Offset: 0x0002D10D
		private void doublePropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x06000621 RID: 1569 RVA: 0x0002EF16 File Offset: 0x0002D116
		private void intPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x06000622 RID: 1570 RVA: 0x0002EF1F File Offset: 0x0002D11F
		private void uintPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x06000623 RID: 1571 RVA: 0x0002EF28 File Offset: 0x0002D128
		private void ColorPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_0(propertyName);
		}

		// Token: 0x06000624 RID: 1572 RVA: 0x0002EF31 File Offset: 0x0002D131
		private void HandleWidgetPropertyChangeOf_widget_1_0_0(string propertyName)
		{
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root_SelectionSelector.IsEnabled = this._widget_1_0_0.IsEnabled;
				return;
			}
		}

		// Token: 0x06000625 RID: 1573 RVA: 0x0002EF57 File Offset: 0x0002D157
		private void PropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x06000626 RID: 1574 RVA: 0x0002EF60 File Offset: 0x0002D160
		private void boolPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x06000627 RID: 1575 RVA: 0x0002EF69 File Offset: 0x0002D169
		private void floatPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x06000628 RID: 1576 RVA: 0x0002EF72 File Offset: 0x0002D172
		private void Vec2PropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x06000629 RID: 1577 RVA: 0x0002EF7B File Offset: 0x0002D17B
		private void Vector2PropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x0600062A RID: 1578 RVA: 0x0002EF84 File Offset: 0x0002D184
		private void doublePropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x0600062B RID: 1579 RVA: 0x0002EF8D File Offset: 0x0002D18D
		private void intPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x0600062C RID: 1580 RVA: 0x0002EF96 File Offset: 0x0002D196
		private void uintPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x0600062D RID: 1581 RVA: 0x0002EF9F File Offset: 0x0002D19F
		private void ColorPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0_1(propertyName);
		}

		// Token: 0x0600062E RID: 1582 RVA: 0x0002EFA8 File Offset: 0x0002D1A8
		private void HandleWidgetPropertyChangeOf_widget_1_0_1(string propertyName)
		{
			if (propertyName == "IsDisabled")
			{
				this._datasource_Root_SelectionSelector.IsEnabled = this._widget_1_0_1.IsDisabled;
				return;
			}
		}

		// Token: 0x0600062F RID: 1583 RVA: 0x0002EFCE File Offset: 0x0002D1CE
		private void PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000630 RID: 1584 RVA: 0x0002EFD7 File Offset: 0x0002D1D7
		private void boolPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000631 RID: 1585 RVA: 0x0002EFE0 File Offset: 0x0002D1E0
		private void floatPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000632 RID: 1586 RVA: 0x0002EFE9 File Offset: 0x0002D1E9
		private void Vec2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000633 RID: 1587 RVA: 0x0002EFF2 File Offset: 0x0002D1F2
		private void Vector2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000634 RID: 1588 RVA: 0x0002EFFB File Offset: 0x0002D1FB
		private void doublePropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000635 RID: 1589 RVA: 0x0002F004 File Offset: 0x0002D204
		private void intPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000636 RID: 1590 RVA: 0x0002F00D File Offset: 0x0002D20D
		private void uintPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000637 RID: 1591 RVA: 0x0002F016 File Offset: 0x0002D216
		private void ColorPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000638 RID: 1592 RVA: 0x0002F01F File Offset: 0x0002D21F
		private void HandleWidgetPropertyChangeOf_widget_2_0(string propertyName)
		{
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root_SelectionSelector.IsEnabled = this._widget_2_0.IsEnabled;
				return;
			}
		}

		// Token: 0x06000639 RID: 1593 RVA: 0x0002F045 File Offset: 0x0002D245
		private void ViewModelPropertyChangedListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x0600063A RID: 1594 RVA: 0x0002F053 File Offset: 0x0002D253
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x0600063B RID: 1595 RVA: 0x0002F062 File Offset: 0x0002D262
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x0600063C RID: 1596 RVA: 0x0002F071 File Offset: 0x0002D271
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x0600063D RID: 1597 RVA: 0x0002F080 File Offset: 0x0002D280
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x0600063E RID: 1598 RVA: 0x0002F08F File Offset: 0x0002D28F
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x0600063F RID: 1599 RVA: 0x0002F09E File Offset: 0x0002D29E
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x06000640 RID: 1600 RVA: 0x0002F0AD File Offset: 0x0002D2AD
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x06000641 RID: 1601 RVA: 0x0002F0BC File Offset: 0x0002D2BC
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(e.PropertyName);
		}

		// Token: 0x06000642 RID: 1602 RVA: 0x0002F0CC File Offset: 0x0002D2CC
		private void HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(string propertyName)
		{
			if (propertyName == "ItemList")
			{
				this.RefreshDataSource_datasource_Root_SelectionSelector_ItemList(this._datasource_Root_SelectionSelector.ItemList);
				return;
			}
			if (propertyName == "IsEnabled")
			{
				this._widget_0_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
				this._widget_1_0_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
				this._widget_1_0_1.IsDisabled = this._datasource_Root_SelectionSelector.IsEnabled;
				this._widget_2_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
				return;
			}
			if (propertyName == "SelectedIndex")
			{
				this._widget_1.CurrentSelectedIndex = this._datasource_Root_SelectionSelector.SelectedIndex;
				return;
			}
		}

		// Token: 0x06000643 RID: 1603 RVA: 0x0002F182 File Offset: 0x0002D382
		private void ViewModelPropertyChangedListenerOf_datasource_Root_Hint(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06000644 RID: 1604 RVA: 0x0002F190 File Offset: 0x0002D390
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06000645 RID: 1605 RVA: 0x0002F19F File Offset: 0x0002D39F
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06000646 RID: 1606 RVA: 0x0002F1AE File Offset: 0x0002D3AE
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06000647 RID: 1607 RVA: 0x0002F1BD File Offset: 0x0002D3BD
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06000648 RID: 1608 RVA: 0x0002F1CC File Offset: 0x0002D3CC
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06000649 RID: 1609 RVA: 0x0002F1DB File Offset: 0x0002D3DB
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x0600064A RID: 1610 RVA: 0x0002F1EA File Offset: 0x0002D3EA
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x0600064B RID: 1611 RVA: 0x0002F1F9 File Offset: 0x0002D3F9
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x0600064C RID: 1612 RVA: 0x0002F208 File Offset: 0x0002D408
		private void HandleViewModelPropertyChangeOf_datasource_Root_Hint(string propertyName)
		{
		}

		// Token: 0x0600064D RID: 1613 RVA: 0x0002F20A File Offset: 0x0002D40A
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600064E RID: 1614 RVA: 0x0002F218 File Offset: 0x0002D418
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600064F RID: 1615 RVA: 0x0002F227 File Offset: 0x0002D427
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000650 RID: 1616 RVA: 0x0002F236 File Offset: 0x0002D436
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000651 RID: 1617 RVA: 0x0002F245 File Offset: 0x0002D445
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000652 RID: 1618 RVA: 0x0002F254 File Offset: 0x0002D454
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000653 RID: 1619 RVA: 0x0002F263 File Offset: 0x0002D463
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000654 RID: 1620 RVA: 0x0002F272 File Offset: 0x0002D472
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000655 RID: 1621 RVA: 0x0002F281 File Offset: 0x0002D481
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000656 RID: 1622 RVA: 0x0002F290 File Offset: 0x0002D490
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "SelectionSelector")
			{
				this.RefreshDataSource_datasource_Root_SelectionSelector(this._datasource_Root.SelectionSelector);
				return;
			}
			if (propertyName == "Hint")
			{
				this.RefreshDataSource_datasource_Root_Hint(this._datasource_Root.Hint);
				return;
			}
		}

		// Token: 0x06000657 RID: 1623 RVA: 0x0002F2D0 File Offset: 0x0002D4D0
		public void OnList_datasource_Root_SelectionSelector_ItemListChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_1_1_0_0_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_1_0_0_0_0.GetChild(i);
					((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_1_0_0_0_0.GetChild(i);
					((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_1_0_0_0_0.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_SelectionSelector_ItemList.Count; j++)
				{
					SelectorItemVM bindingObject = this._datasource_Root_SelectionSelector_ItemList[j];
					this._widget_1_1_0_0_0_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate = new CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate);
				SelectorItemVM selectorItemVM = this._datasource_Root_SelectionSelector_ItemList[e.NewIndex];
				generatedWidgetData.Data = selectorItemVM;
				campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_1_1_0_0_0_0.AddChildAtIndex(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate, e.NewIndex);
				campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.CreateWidgets();
				campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetIds();
				campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetAttributes();
				campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetDataSource(selectorItemVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_1_1_0_0_0_0.GetChild(e.NewIndex);
				((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_1_1_0_0_0_0.GetChild(e.NewIndex);
				((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child4).SetDataSource(null);
				this._widget_1_1_0_0_0_0.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06000658 RID: 1624 RVA: 0x0002F46C File Offset: 0x0002D66C
		private void RefreshDataSource_datasource_Root_SelectionSelector(CampaignOptionSelectorVM newDataSource)
		{
			if (this._datasource_Root_SelectionSelector != null)
			{
				this._datasource_Root_SelectionSelector.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectionSelector;
				this._widget_0_0.EventFire -= this.EventListenerOf_widget_0_0;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_1.EventFire -= this.EventListenerOf_widget_1;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0_1;
				this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
				this._widget_2_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0;
				if (this._datasource_Root_SelectionSelector_ItemList != null)
				{
					this._datasource_Root_SelectionSelector_ItemList.ListChanged -= this.OnList_datasource_Root_SelectionSelector_ItemListChanged;
					for (int i = this._widget_1_1_0_0_0_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_1_0_0_0_0.GetChild(i);
						((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_1_1_0_0_0_0.GetChild(i);
						((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child2).SetDataSource(null);
						this._widget_1_1_0_0_0_0.RemoveChild(child2);
					}
					this._datasource_Root_SelectionSelector_ItemList = null;
				}
				this._datasource_Root_SelectionSelector = null;
			}
			this._datasource_Root_SelectionSelector = newDataSource;
			this._datasource_Root_SelectionSelector = this._datasource_Root.SelectionSelector;
			if (this._datasource_Root_SelectionSelector != null)
			{
				this._datasource_Root_SelectionSelector.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectionSelector;
				this._datasource_Root_SelectionSelector.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectionSelector;
				this._widget_0_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
				this._widget_0_0.EventFire += this.EventListenerOf_widget_0_0;
				this._widget_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_1.CurrentSelectedIndex = this._datasource_Root_SelectionSelector.SelectedIndex;
				this._widget_1.EventFire += this.EventListenerOf_widget_1;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
				this._widget_1_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0_0;
				this._widget_1_0_1.IsDisabled = this._datasource_Root_SelectionSelector.IsEnabled;
				this._widget_1_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0_1;
				this._widget_1_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0_1;
				this._widget_2_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
				this._widget_2_0.EventFire += this.EventListenerOf_widget_2_0;
				this._widget_2_0.PropertyChanged += this.PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2_0;
				this._datasource_Root_SelectionSelector_ItemList = this._datasource_Root_SelectionSelector.ItemList;
				if (this._datasource_Root_SelectionSelector_ItemList != null)
				{
					this._datasource_Root_SelectionSelector_ItemList.ListChanged += this.OnList_datasource_Root_SelectionSelector_ItemListChanged;
					for (int j = 0; j < this._datasource_Root_SelectionSelector_ItemList.Count; j++)
					{
						CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate = new CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate);
						SelectorItemVM selectorItemVM = this._datasource_Root_SelectionSelector_ItemList[j];
						generatedWidgetData.Data = selectorItemVM;
						campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_1_1_0_0_0_0.AddChildAtIndex(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate, j);
						campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.CreateWidgets();
						campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetIds();
						campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetAttributes();
						campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetDataSource(selectorItemVM);
					}
				}
			}
		}

		// Token: 0x06000659 RID: 1625 RVA: 0x00030084 File Offset: 0x0002E284
		private void RefreshDataSource_datasource_Root_Hint(HintViewModel newDataSource)
		{
			if (this._datasource_Root_Hint != null)
			{
				this._datasource_Root_Hint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
				this._widget_1_0_0_1.EventFire -= this.EventListenerOf_widget_1_0_0_1;
				this._widget_1_0_1_0.EventFire -= this.EventListenerOf_widget_1_0_1_0;
				this._datasource_Root_Hint = null;
			}
			this._datasource_Root_Hint = newDataSource;
			this._datasource_Root_Hint = this._datasource_Root.Hint;
			if (this._datasource_Root_Hint != null)
			{
				this._datasource_Root_Hint.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
				this._widget_1_0_0_1.EventFire += this.EventListenerOf_widget_1_0_0_1;
				this._widget_1_0_1_0.EventFire += this.EventListenerOf_widget_1_0_1_0;
			}
		}

		// Token: 0x0600065A RID: 1626 RVA: 0x000302C0 File Offset: 0x0002E4C0
		private void RefreshDataSource_datasource_Root_SelectionSelector_ItemList(MBBindingList<SelectorItemVM> newDataSource)
		{
			if (this._datasource_Root_SelectionSelector_ItemList != null)
			{
				this._datasource_Root_SelectionSelector_ItemList.ListChanged -= this.OnList_datasource_Root_SelectionSelector_ItemListChanged;
				for (int i = this._widget_1_1_0_0_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_1_0_0_0_0.GetChild(i);
					((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_1_0_0_0_0.GetChild(i);
					((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_1_0_0_0_0.RemoveChild(child2);
				}
				this._datasource_Root_SelectionSelector_ItemList = null;
			}
			this._datasource_Root_SelectionSelector_ItemList = newDataSource;
			this._datasource_Root_SelectionSelector_ItemList = this._datasource_Root_SelectionSelector.ItemList;
			if (this._datasource_Root_SelectionSelector_ItemList != null)
			{
				this._datasource_Root_SelectionSelector_ItemList.ListChanged += this.OnList_datasource_Root_SelectionSelector_ItemListChanged;
				for (int j = 0; j < this._datasource_Root_SelectionSelector_ItemList.Count; j++)
				{
					CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate = new CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate);
					SelectorItemVM selectorItemVM = this._datasource_Root_SelectionSelector_ItemList[j];
					generatedWidgetData.Data = selectorItemVM;
					campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_1_1_0_0_0_0.AddChildAtIndex(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate, j);
					campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.CreateWidgets();
					campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetIds();
					campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetAttributes();
					campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetDataSource(selectorItemVM);
				}
			}
		}

		// Token: 0x0600065B RID: 1627 RVA: 0x000303FC File Offset: 0x0002E5FC
		private void RefreshDataSource_datasource_Root(CampaignOptionItemVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_SelectionSelector != null)
				{
					this._datasource_Root_SelectionSelector.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectionSelector;
					this._widget_0_0.EventFire -= this.EventListenerOf_widget_0_0;
					this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
					this._widget_1.EventFire -= this.EventListenerOf_widget_1;
					this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
					this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
					this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
					this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
					this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
					this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
					this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
					this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
					this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
					this._widget_1_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0_1;
					this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
					this._widget_2_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0;
					if (this._datasource_Root_SelectionSelector_ItemList != null)
					{
						this._datasource_Root_SelectionSelector_ItemList.ListChanged -= this.OnList_datasource_Root_SelectionSelector_ItemListChanged;
						for (int i = this._widget_1_1_0_0_0_0.ChildCount - 1; i >= 0; i--)
						{
							Widget child = this._widget_1_1_0_0_0_0.GetChild(i);
							((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child).OnBeforeRemovedChild(child);
							Widget child2 = this._widget_1_1_0_0_0_0.GetChild(i);
							((CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate)child2).SetDataSource(null);
							this._widget_1_1_0_0_0_0.RemoveChild(child2);
						}
						this._datasource_Root_SelectionSelector_ItemList = null;
					}
					this._datasource_Root_SelectionSelector = null;
				}
				if (this._datasource_Root_Hint != null)
				{
					this._datasource_Root_Hint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
					this._widget_1_0_0_1.EventFire -= this.EventListenerOf_widget_1_0_0_1;
					this._widget_1_0_1_0.EventFire -= this.EventListenerOf_widget_1_0_1_0;
					this._datasource_Root_Hint = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._datasource_Root_SelectionSelector = this._datasource_Root.SelectionSelector;
				if (this._datasource_Root_SelectionSelector != null)
				{
					this._datasource_Root_SelectionSelector.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectionSelector;
					this._datasource_Root_SelectionSelector.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectionSelector;
					this._widget_0_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
					this._widget_0_0.EventFire += this.EventListenerOf_widget_0_0;
					this._widget_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0;
					this._widget_1.CurrentSelectedIndex = this._datasource_Root_SelectionSelector.SelectedIndex;
					this._widget_1.EventFire += this.EventListenerOf_widget_1;
					this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
					this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
					this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
					this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
					this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
					this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
					this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
					this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
					this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
					this._widget_1_0_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
					this._widget_1_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0_0;
					this._widget_1_0_1.IsDisabled = this._datasource_Root_SelectionSelector.IsEnabled;
					this._widget_1_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0_1;
					this._widget_1_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0_1;
					this._widget_2_0.IsEnabled = this._datasource_Root_SelectionSelector.IsEnabled;
					this._widget_2_0.EventFire += this.EventListenerOf_widget_2_0;
					this._widget_2_0.PropertyChanged += this.PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2_0;
					this._widget_2_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2_0;
					this._datasource_Root_SelectionSelector_ItemList = this._datasource_Root_SelectionSelector.ItemList;
					if (this._datasource_Root_SelectionSelector_ItemList != null)
					{
						this._datasource_Root_SelectionSelector_ItemList.ListChanged += this.OnList_datasource_Root_SelectionSelector_ItemListChanged;
						for (int j = 0; j < this._datasource_Root_SelectionSelector_ItemList.Count; j++)
						{
							CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate = new CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate(base.Context);
							GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate);
							SelectorItemVM selectorItemVM = this._datasource_Root_SelectionSelector_ItemList[j];
							generatedWidgetData.Data = selectorItemVM;
							campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.AddComponent(generatedWidgetData);
							this._widget_1_1_0_0_0_0.AddChildAtIndex(campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate, j);
							campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.CreateWidgets();
							campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetIds();
							campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetAttributes();
							campaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_3_ItemTemplate.SetDataSource(selectorItemVM);
						}
					}
				}
				this._datasource_Root_Hint = this._datasource_Root.Hint;
				if (this._datasource_Root_Hint != null)
				{
					this._datasource_Root_Hint.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
					this._widget_1_0_0_1.EventFire += this.EventListenerOf_widget_1_0_0_1;
					this._widget_1_0_1_0.EventFire += this.EventListenerOf_widget_1_0_1_0;
				}
			}
		}

		// Token: 0x0400013E RID: 318
		private ListPanel _widget;

		// Token: 0x0400013F RID: 319
		private Widget _widget_0;

		// Token: 0x04000140 RID: 320
		private ButtonWidget _widget_0_0;

		// Token: 0x04000141 RID: 321
		private AnimatedDropdownWidget _widget_1;

		// Token: 0x04000142 RID: 322
		private Widget _widget_1_0;

		// Token: 0x04000143 RID: 323
		private ButtonWidget _widget_1_0_0;

		// Token: 0x04000144 RID: 324
		private ScrollingRichTextWidget _widget_1_0_0_0;

		// Token: 0x04000145 RID: 325
		private HintWidget _widget_1_0_0_1;

		// Token: 0x04000146 RID: 326
		private Widget _widget_1_0_1;

		// Token: 0x04000147 RID: 327
		private HintWidget _widget_1_0_1_0;

		// Token: 0x04000148 RID: 328
		private Widget _widget_1_1;

		// Token: 0x04000149 RID: 329
		private BrushWidget _widget_1_1_0;

		// Token: 0x0400014A RID: 330
		private ScrollablePanel _widget_1_1_0_0;

		// Token: 0x0400014B RID: 331
		private Widget _widget_1_1_0_0_0;

		// Token: 0x0400014C RID: 332
		private ListPanel _widget_1_1_0_0_0_0;

		// Token: 0x0400014D RID: 333
		private ScrollbarWidget _widget_1_1_0_1;

		// Token: 0x0400014E RID: 334
		private Widget _widget_1_1_0_1_0;

		// Token: 0x0400014F RID: 335
		private ImageWidget _widget_1_1_0_1_1;

		// Token: 0x04000150 RID: 336
		private Widget _widget_2;

		// Token: 0x04000151 RID: 337
		private ButtonWidget _widget_2_0;

		// Token: 0x04000152 RID: 338
		private CampaignOptionItemVM _datasource_Root;

		// Token: 0x04000153 RID: 339
		private CampaignOptionSelectorVM _datasource_Root_SelectionSelector;

		// Token: 0x04000154 RID: 340
		private MBBindingList<SelectorItemVM> _datasource_Root_SelectionSelector_ItemList;

		// Token: 0x04000155 RID: 341
		private HintViewModel _datasource_Root_Hint;
	}
}
