using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia.List;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000077 RID: 119
	public class EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaFactionPageVM_Dependency_6_ItemTemplate : ButtonWidget
	{
		// Token: 0x06001ADC RID: 6876 RVA: 0x000C4339 File Offset: 0x000C2539
		public EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaFactionPageVM_Dependency_6_ItemTemplate(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001ADD RID: 6877 RVA: 0x000C4344 File Offset: 0x000C2544
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ImageWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new ScrollingRichTextWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_2 = new ScrollingRichTextWidget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_3 = new HintWidget(base.Context);
			this._widget.AddChild(this._widget_3);
		}

		// Token: 0x06001ADE RID: 6878 RVA: 0x000C43E0 File Offset: 0x000C25E0
		public void SetIds()
		{
			base.Id = "DropdownItemButton";
		}

		// Token: 0x06001ADF RID: 6879 RVA: 0x000C43F0 File Offset: 0x000C25F0
		public void SetAttributes()
		{
			base.DoNotUseCustomScale = true;
			base.DoNotPassEventsToChildren = true;
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedHeight = 29f;
			base.MarginLeft = 10f;
			base.MarginRight = 10f;
			base.HorizontalAlignment = HorizontalAlignment.Center;
			base.VerticalAlignment = VerticalAlignment.Bottom;
			base.ButtonType = ButtonType.Radio;
			base.UpdateChildrenStates = true;
			base.Brush = base.Context.GetBrush("Standard.DropdownItem.SoundBrush");
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.MarginLeft = 5f;
			this._widget_0.MarginRight = 5f;
			this._widget_0.Brush = base.Context.GetBrush("Standard.DropdownItem.Flat");
			this._widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1.MarginLeft = 7f;
			this._widget_1.MarginRight = 7f;
			this._widget_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1.Brush = base.Context.GetBrush("Standard.DropdownItem.Text");
			this._widget_1.IsAutoScrolling = false;
			this._widget_1.ScrollOnHoverWidget = this._widget.FindChild(new BindingPath("..\\DropdownItemButton"));
			this._widget_1.IsEnabled = true;
			this._widget_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_2.MarginLeft = 7f;
			this._widget_2.MarginRight = 7f;
			this._widget_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2.Brush = base.Context.GetBrush("Standard.DropdownItem.Text");
			this._widget_2.IsAutoScrolling = false;
			this._widget_2.ScrollOnHoverWidget = this._widget.FindChild(new BindingPath("..\\DropdownItemButton"));
			this._widget_2.IsEnabled = false;
			this._widget_3.DoNotAcceptEvents = true;
			this._widget_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.HeightSizePolicy = SizePolicy.StretchToParent;
		}

		// Token: 0x06001AE0 RID: 6880 RVA: 0x000C462C File Offset: 0x000C282C
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				if (this._datasource_Root_Hint != null)
				{
					this._datasource_Root_Hint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
					this._widget_3.EventFire -= this.EventListenerOf_widget_3;
					this._datasource_Root_Hint = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06001AE1 RID: 6881 RVA: 0x000C4A7F File Offset: 0x000C2C7F
		public void SetDataSource(EncyclopediaListSelectorItemVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06001AE2 RID: 6882 RVA: 0x000C4A88 File Offset: 0x000C2C88
		private void EventListenerOf_widget_3(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_Hint.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_Hint.ExecuteEndHint();
			}
		}

		// Token: 0x06001AE3 RID: 6883 RVA: 0x000C4ABA File Offset: 0x000C2CBA
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AE4 RID: 6884 RVA: 0x000C4AC3 File Offset: 0x000C2CC3
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AE5 RID: 6885 RVA: 0x000C4ACC File Offset: 0x000C2CCC
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AE6 RID: 6886 RVA: 0x000C4AD5 File Offset: 0x000C2CD5
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AE7 RID: 6887 RVA: 0x000C4ADE File Offset: 0x000C2CDE
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AE8 RID: 6888 RVA: 0x000C4AE7 File Offset: 0x000C2CE7
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AE9 RID: 6889 RVA: 0x000C4AF0 File Offset: 0x000C2CF0
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AEA RID: 6890 RVA: 0x000C4AF9 File Offset: 0x000C2CF9
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AEB RID: 6891 RVA: 0x000C4B02 File Offset: 0x000C2D02
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001AEC RID: 6892 RVA: 0x000C4B0B File Offset: 0x000C2D0B
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root.CanBeSelected = this._widget.IsEnabled;
				return;
			}
		}

		// Token: 0x06001AED RID: 6893 RVA: 0x000C4B31 File Offset: 0x000C2D31
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AEE RID: 6894 RVA: 0x000C4B3A File Offset: 0x000C2D3A
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AEF RID: 6895 RVA: 0x000C4B43 File Offset: 0x000C2D43
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AF0 RID: 6896 RVA: 0x000C4B4C File Offset: 0x000C2D4C
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AF1 RID: 6897 RVA: 0x000C4B55 File Offset: 0x000C2D55
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AF2 RID: 6898 RVA: 0x000C4B5E File Offset: 0x000C2D5E
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AF3 RID: 6899 RVA: 0x000C4B67 File Offset: 0x000C2D67
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AF4 RID: 6900 RVA: 0x000C4B70 File Offset: 0x000C2D70
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AF5 RID: 6901 RVA: 0x000C4B79 File Offset: 0x000C2D79
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06001AF6 RID: 6902 RVA: 0x000C4B84 File Offset: 0x000C2D84
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.StringItem = this._widget_1.Text;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.CanBeSelected = this._widget_1.IsVisible;
				return;
			}
		}

		// Token: 0x06001AF7 RID: 6903 RVA: 0x000C4BD9 File Offset: 0x000C2DD9
		private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AF8 RID: 6904 RVA: 0x000C4BE2 File Offset: 0x000C2DE2
		private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AF9 RID: 6905 RVA: 0x000C4BEB File Offset: 0x000C2DEB
		private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AFA RID: 6906 RVA: 0x000C4BF4 File Offset: 0x000C2DF4
		private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AFB RID: 6907 RVA: 0x000C4BFD File Offset: 0x000C2DFD
		private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AFC RID: 6908 RVA: 0x000C4C06 File Offset: 0x000C2E06
		private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AFD RID: 6909 RVA: 0x000C4C0F File Offset: 0x000C2E0F
		private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AFE RID: 6910 RVA: 0x000C4C18 File Offset: 0x000C2E18
		private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001AFF RID: 6911 RVA: 0x000C4C21 File Offset: 0x000C2E21
		private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06001B00 RID: 6912 RVA: 0x000C4C2C File Offset: 0x000C2E2C
		private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.StringItem = this._widget_2.Text;
				return;
			}
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.CanBeSelected = this._widget_2.IsHidden;
				return;
			}
		}

		// Token: 0x06001B01 RID: 6913 RVA: 0x000C4C81 File Offset: 0x000C2E81
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B02 RID: 6914 RVA: 0x000C4C8F File Offset: 0x000C2E8F
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B03 RID: 6915 RVA: 0x000C4C9E File Offset: 0x000C2E9E
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B04 RID: 6916 RVA: 0x000C4CAD File Offset: 0x000C2EAD
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B05 RID: 6917 RVA: 0x000C4CBC File Offset: 0x000C2EBC
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B06 RID: 6918 RVA: 0x000C4CCB File Offset: 0x000C2ECB
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B07 RID: 6919 RVA: 0x000C4CDA File Offset: 0x000C2EDA
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B08 RID: 6920 RVA: 0x000C4CE9 File Offset: 0x000C2EE9
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B09 RID: 6921 RVA: 0x000C4CF8 File Offset: 0x000C2EF8
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001B0A RID: 6922 RVA: 0x000C4D08 File Offset: 0x000C2F08
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Hint")
			{
				this.RefreshDataSource_datasource_Root_Hint(this._datasource_Root.Hint);
				return;
			}
			if (propertyName == "CanBeSelected")
			{
				this._widget.IsEnabled = this._datasource_Root.CanBeSelected;
				this._widget_1.IsVisible = this._datasource_Root.CanBeSelected;
				this._widget_2.IsHidden = this._datasource_Root.CanBeSelected;
				return;
			}
			if (propertyName == "StringItem")
			{
				this._widget_1.Text = this._datasource_Root.StringItem;
				this._widget_2.Text = this._datasource_Root.StringItem;
				return;
			}
		}

		// Token: 0x06001B0B RID: 6923 RVA: 0x000C4DBE File Offset: 0x000C2FBE
		private void ViewModelPropertyChangedListenerOf_datasource_Root_Hint(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B0C RID: 6924 RVA: 0x000C4DCC File Offset: 0x000C2FCC
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B0D RID: 6925 RVA: 0x000C4DDB File Offset: 0x000C2FDB
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B0E RID: 6926 RVA: 0x000C4DEA File Offset: 0x000C2FEA
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B0F RID: 6927 RVA: 0x000C4DF9 File Offset: 0x000C2FF9
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B10 RID: 6928 RVA: 0x000C4E08 File Offset: 0x000C3008
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B11 RID: 6929 RVA: 0x000C4E17 File Offset: 0x000C3017
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B12 RID: 6930 RVA: 0x000C4E26 File Offset: 0x000C3026
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B13 RID: 6931 RVA: 0x000C4E35 File Offset: 0x000C3035
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
		}

		// Token: 0x06001B14 RID: 6932 RVA: 0x000C4E44 File Offset: 0x000C3044
		private void HandleViewModelPropertyChangeOf_datasource_Root_Hint(string propertyName)
		{
		}

		// Token: 0x06001B15 RID: 6933 RVA: 0x000C4E48 File Offset: 0x000C3048
		private void RefreshDataSource_datasource_Root(EncyclopediaListSelectorItemVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				if (this._datasource_Root_Hint != null)
				{
					this._datasource_Root_Hint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
					this._widget_3.EventFire -= this.EventListenerOf_widget_3;
					this._datasource_Root_Hint = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.IsEnabled = this._datasource_Root.CanBeSelected;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._widget_1.Text = this._datasource_Root.StringItem;
				this._widget_1.IsVisible = this._datasource_Root.CanBeSelected;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_2.Text = this._datasource_Root.StringItem;
				this._widget_2.IsHidden = this._datasource_Root.CanBeSelected;
				this._widget_2.PropertyChanged += this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2;
				this._datasource_Root_Hint = this._datasource_Root.Hint;
				if (this._datasource_Root_Hint != null)
				{
					this._datasource_Root_Hint.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
					this._datasource_Root_Hint.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
					this._widget_3.EventFire += this.EventListenerOf_widget_3;
				}
			}
		}

		// Token: 0x06001B16 RID: 6934 RVA: 0x000C575C File Offset: 0x000C395C
		private void RefreshDataSource_datasource_Root_Hint(HintViewModel newDataSource)
		{
			if (this._datasource_Root_Hint != null)
			{
				this._datasource_Root_Hint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
				this._widget_3.EventFire -= this.EventListenerOf_widget_3;
				this._datasource_Root_Hint = null;
			}
			this._datasource_Root_Hint = newDataSource;
			this._datasource_Root_Hint = this._datasource_Root.Hint;
			if (this._datasource_Root_Hint != null)
			{
				this._datasource_Root_Hint.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
				this._datasource_Root_Hint.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
				this._widget_3.EventFire += this.EventListenerOf_widget_3;
			}
		}

		// Token: 0x04000593 RID: 1427
		private ButtonWidget _widget;

		// Token: 0x04000594 RID: 1428
		private ImageWidget _widget_0;

		// Token: 0x04000595 RID: 1429
		private ScrollingRichTextWidget _widget_1;

		// Token: 0x04000596 RID: 1430
		private ScrollingRichTextWidget _widget_2;

		// Token: 0x04000597 RID: 1431
		private HintWidget _widget_3;

		// Token: 0x04000598 RID: 1432
		private EncyclopediaListSelectorItemVM _datasource_Root;

		// Token: 0x04000599 RID: 1433
		private HintViewModel _datasource_Root_Hint;
	}
}
