using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu;
using TaleWorlds.CampaignSystem.ViewModelCollection.Input;
using TaleWorlds.CampaignSystem.ViewModelCollection.Quests;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Tutorial;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000090 RID: 144
	public class GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_4_GameMenuItem__InheritedPrefab : GameMenuItemWidget
	{
		// Token: 0x06001F12 RID: 7954 RVA: 0x000E32FC File Offset: 0x000E14FC
		public GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_4_GameMenuItem__InheritedPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001F13 RID: 7955 RVA: 0x000E3308 File Offset: 0x000E1508
		public virtual void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ButtonWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new ImageWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_1 = new ListPanel(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_2 = new TutorialHighlightItemBrushWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_2);
			this._widget_0_3 = new RichTextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_3);
			this._widget_0_3_0 = new Widget(base.Context);
			this._widget_0_3.AddChild(this._widget_0_3_0);
			this._widget_0_3_0_0 = new InputKeyVisualWidget(base.Context);
			this._widget_0_3_0.AddChild(this._widget_0_3_0_0);
			this._widget_0_4 = new HintWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_4);
			this._widget_0_5 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_5);
			this._widget_1 = new HintWidget(base.Context);
			this._widget.AddChild(this._widget_1);
		}

		// Token: 0x06001F14 RID: 7956 RVA: 0x000E3470 File Offset: 0x000E1670
		public virtual void SetIds()
		{
			base.Id = "ParentGameMenuItemWidget";
			this._widget_0.Id = "ParentButton";
			this._widget_0_0.Id = "LeaveTypeIcon";
			this._widget_0_3.Id = "ItemRichTextWidget";
		}

		// Token: 0x06001F15 RID: 7957 RVA: 0x000E34B0 File Offset: 0x000E16B0
		public virtual void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			base.HorizontalAlignment = HorizontalAlignment.Center;
			base.ParentButton = this._widget_0;
			base.LeaveTypeIcon = this._widget_0_0;
			base.WaitStateWidget = this._widget_0.FindChild("WaitStateWidget") as BrushWidget;
			base.ItemRichTextWidget = this._widget_0_3;
			base.DefaultTextBrush = base.Context.GetBrush("GameMenu.Items.Text.Default");
			base.HoveredTextBrush = base.Context.GetBrush("GameMenu.Items.Text.Hovered");
			base.PressedTextBrush = base.Context.GetBrush("GameMenu.Items.Text.Pressed");
			base.DisabledTextBrush = base.Context.GetBrush("GameMenu.Items.Text.Disabled");
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.Brush = base.Context.GetBrush("GameMenu.Button");
			this._widget_0.UpdateChildrenStates = true;
			this._widget_0_0.DoNotAcceptEvents = true;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedWidth = 56f;
			this._widget_0_0.SuggestedHeight = 42f;
			this._widget_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0.Brush = base.Context.GetBrush("GameMenu.LeaveType");
			this._widget_0_0.OverrideDefaultStateSwitchingEnabled = true;
			this._widget_0_1.DoNotAcceptEvents = true;
			this._widget_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1.MarginRight = 10f;
			this._widget_0_1.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_2.SuggestedWidth = 0f;
			this._widget_0_2.SuggestedHeight = 0f;
			this._widget_0_2.Brush = base.Context.GetBrush("TutorialHighlightBrush");
			this._widget_0_2.IsEnabled = false;
			this._widget_0_2.IsVisible = false;
			this._widget_0_2.CustomSizeSyncTarget = this._widget_0_3;
			this._widget_0_2.DoNotOverrideWidth = true;
			this._widget_0_3.DoNotAcceptEvents = true;
			this._widget_0_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_3.Brush = base.Context.GetBrush("GameMenu.Items.Text.Default");
			this._widget_0_3.MarginLeft = 55f;
			this._widget_0_3.MarginRight = 35f;
			this._widget_0_3_0.DoNotAcceptEvents = true;
			this._widget_0_3_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_0.SuggestedWidth = 40f;
			this._widget_0_3_0.SuggestedHeight = 40f;
			this._widget_0_3_0.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_3_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_3_0.PositionXOffset = 38f;
			this._widget_0_3_0_0.DoNotAcceptEvents = true;
			this._widget_0_3_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_0_0.SuggestedWidth = 48f;
			this._widget_0_3_0_0.SuggestedHeight = 48f;
			this._widget_0_3_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_3_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_4.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_4.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_4.SuggestedHeight = 40f;
			this._widget_0_4.IsEnabled = false;
			this._widget_0_5.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_5.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_5.SuggestedHeight = 2f;
			this._widget_0_5.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_5.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_5.Sprite = base.Context.SpriteData.GetSprite("GradientDivider_9");
			this._widget_0_5.AlphaFactor = 0.4f;
			this._widget_0_5.MarginLeft = 10f;
			this._widget_0_5.MarginRight = 10f;
			this._widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1.SuggestedHeight = 40f;
			this._widget_1.IsEnabled = false;
		}

		// Token: 0x06001F16 RID: 7958 RVA: 0x000E3948 File Offset: 0x000E1B48
		public virtual void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_2;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3_0;
				if (this._datasource_Root_Quests != null)
				{
					this._datasource_Root_Quests.ListChanged -= this.OnList_datasource_Root_QuestsChanged;
					for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_1.GetChild(i);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)this._widget_0_1.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_Quests = null;
				}
				if (this._datasource_Root_ShortcutKey != null)
				{
					this._datasource_Root_ShortcutKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ShortcutKey;
					this._widget_0_3_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3_0_0;
					this._datasource_Root_ShortcutKey = null;
				}
				if (this._datasource_Root_ItemHint != null)
				{
					this._datasource_Root_ItemHint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ItemHint;
					this._widget_0_4.EventFire -= this.EventListenerOf_widget_0_4;
					this._widget_1.EventFire -= this.EventListenerOf_widget_1;
					this._datasource_Root_ItemHint = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06001F17 RID: 7959 RVA: 0x000E4184 File Offset: 0x000E2384
		public virtual void SetDataSource(GameMenuItemVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06001F18 RID: 7960 RVA: 0x000E418D File Offset: 0x000E238D
		private void EventListenerOf_widget_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteAction();
			}
		}

		// Token: 0x06001F19 RID: 7961 RVA: 0x000E41A7 File Offset: 0x000E23A7
		private void EventListenerOf_widget_0_4(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_ItemHint.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_ItemHint.ExecuteEndHint();
			}
		}

		// Token: 0x06001F1A RID: 7962 RVA: 0x000E41D9 File Offset: 0x000E23D9
		private void EventListenerOf_widget_1(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_ItemHint.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_ItemHint.ExecuteEndHint();
			}
		}

		// Token: 0x06001F1B RID: 7963 RVA: 0x000E420B File Offset: 0x000E240B
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F1C RID: 7964 RVA: 0x000E4214 File Offset: 0x000E2414
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F1D RID: 7965 RVA: 0x000E421D File Offset: 0x000E241D
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F1E RID: 7966 RVA: 0x000E4226 File Offset: 0x000E2426
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F1F RID: 7967 RVA: 0x000E422F File Offset: 0x000E242F
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F20 RID: 7968 RVA: 0x000E4238 File Offset: 0x000E2438
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F21 RID: 7969 RVA: 0x000E4241 File Offset: 0x000E2441
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F22 RID: 7970 RVA: 0x000E424A File Offset: 0x000E244A
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F23 RID: 7971 RVA: 0x000E4253 File Offset: 0x000E2453
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06001F24 RID: 7972 RVA: 0x000E425C File Offset: 0x000E245C
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "IsWaitActive")
			{
				this._datasource_Root.IsWaitActive = this._widget.IsWaitActive;
				return;
			}
			if (propertyName == "ItemType")
			{
				this._datasource_Root.ItemType = this._widget.ItemType;
				return;
			}
			if (propertyName == "LeaveType")
			{
				this._datasource_Root.OptionLeaveType = this._widget.LeaveType;
				return;
			}
			if (propertyName == "GameMenuStringId")
			{
				this._datasource_Root.GameMenuStringId = this._widget.GameMenuStringId;
				return;
			}
			if (propertyName == "BattleSize")
			{
				this._datasource_Root.BattleSize = this._widget.BattleSize;
				return;
			}
			if (propertyName == "IsNavalBattle")
			{
				this._datasource_Root.IsNavalBattle = this._widget.IsNavalBattle;
				return;
			}
		}

		// Token: 0x06001F25 RID: 7973 RVA: 0x000E4341 File Offset: 0x000E2541
		private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F26 RID: 7974 RVA: 0x000E434A File Offset: 0x000E254A
		private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F27 RID: 7975 RVA: 0x000E4353 File Offset: 0x000E2553
		private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F28 RID: 7976 RVA: 0x000E435C File Offset: 0x000E255C
		private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F29 RID: 7977 RVA: 0x000E4365 File Offset: 0x000E2565
		private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F2A RID: 7978 RVA: 0x000E436E File Offset: 0x000E256E
		private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F2B RID: 7979 RVA: 0x000E4377 File Offset: 0x000E2577
		private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F2C RID: 7980 RVA: 0x000E4380 File Offset: 0x000E2580
		private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F2D RID: 7981 RVA: 0x000E4389 File Offset: 0x000E2589
		private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06001F2E RID: 7982 RVA: 0x000E4392 File Offset: 0x000E2592
		private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
		{
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root.IsEnabled = this._widget_0.IsEnabled;
				return;
			}
		}

		// Token: 0x06001F2F RID: 7983 RVA: 0x000E43B8 File Offset: 0x000E25B8
		private void PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F30 RID: 7984 RVA: 0x000E43C1 File Offset: 0x000E25C1
		private void boolPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F31 RID: 7985 RVA: 0x000E43CA File Offset: 0x000E25CA
		private void floatPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F32 RID: 7986 RVA: 0x000E43D3 File Offset: 0x000E25D3
		private void Vec2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F33 RID: 7987 RVA: 0x000E43DC File Offset: 0x000E25DC
		private void Vector2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F34 RID: 7988 RVA: 0x000E43E5 File Offset: 0x000E25E5
		private void doublePropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F35 RID: 7989 RVA: 0x000E43EE File Offset: 0x000E25EE
		private void intPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F36 RID: 7990 RVA: 0x000E43F7 File Offset: 0x000E25F7
		private void uintPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F37 RID: 7991 RVA: 0x000E4400 File Offset: 0x000E2600
		private void ColorPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
		}

		// Token: 0x06001F38 RID: 7992 RVA: 0x000E4409 File Offset: 0x000E2609
		private void HandleWidgetPropertyChangeOf_widget_0_2(string propertyName)
		{
			if (propertyName == "IsHighlightEnabled")
			{
				this._datasource_Root.IsHighlightEnabled = this._widget_0_2.IsHighlightEnabled;
				return;
			}
		}

		// Token: 0x06001F39 RID: 7993 RVA: 0x000E442F File Offset: 0x000E262F
		private void PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F3A RID: 7994 RVA: 0x000E4438 File Offset: 0x000E2638
		private void boolPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F3B RID: 7995 RVA: 0x000E4441 File Offset: 0x000E2641
		private void floatPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F3C RID: 7996 RVA: 0x000E444A File Offset: 0x000E264A
		private void Vec2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F3D RID: 7997 RVA: 0x000E4453 File Offset: 0x000E2653
		private void Vector2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F3E RID: 7998 RVA: 0x000E445C File Offset: 0x000E265C
		private void doublePropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F3F RID: 7999 RVA: 0x000E4465 File Offset: 0x000E2665
		private void intPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F40 RID: 8000 RVA: 0x000E446E File Offset: 0x000E266E
		private void uintPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F41 RID: 8001 RVA: 0x000E4477 File Offset: 0x000E2677
		private void ColorPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001F42 RID: 8002 RVA: 0x000E4480 File Offset: 0x000E2680
		private void HandleWidgetPropertyChangeOf_widget_0_3(string propertyName)
		{
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root.IsEnabled = this._widget_0_3.IsEnabled;
				return;
			}
			if (propertyName == "Text")
			{
				this._datasource_Root.Item = this._widget_0_3.Text;
				return;
			}
		}

		// Token: 0x06001F43 RID: 8003 RVA: 0x000E44D5 File Offset: 0x000E26D5
		private void PropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F44 RID: 8004 RVA: 0x000E44DE File Offset: 0x000E26DE
		private void boolPropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F45 RID: 8005 RVA: 0x000E44E7 File Offset: 0x000E26E7
		private void floatPropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F46 RID: 8006 RVA: 0x000E44F0 File Offset: 0x000E26F0
		private void Vec2PropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F47 RID: 8007 RVA: 0x000E44F9 File Offset: 0x000E26F9
		private void Vector2PropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F48 RID: 8008 RVA: 0x000E4502 File Offset: 0x000E2702
		private void doublePropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F49 RID: 8009 RVA: 0x000E450B File Offset: 0x000E270B
		private void intPropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F4A RID: 8010 RVA: 0x000E4514 File Offset: 0x000E2714
		private void uintPropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F4B RID: 8011 RVA: 0x000E451D File Offset: 0x000E271D
		private void ColorPropertyChangedListenerOf_widget_0_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0(propertyName);
		}

		// Token: 0x06001F4C RID: 8012 RVA: 0x000E4526 File Offset: 0x000E2726
		private void HandleWidgetPropertyChangeOf_widget_0_3_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsEnabled = this._widget_0_3_0.IsVisible;
				return;
			}
		}

		// Token: 0x06001F4D RID: 8013 RVA: 0x000E454C File Offset: 0x000E274C
		private void PropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F4E RID: 8014 RVA: 0x000E4555 File Offset: 0x000E2755
		private void boolPropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F4F RID: 8015 RVA: 0x000E455E File Offset: 0x000E275E
		private void floatPropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F50 RID: 8016 RVA: 0x000E4567 File Offset: 0x000E2767
		private void Vec2PropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F51 RID: 8017 RVA: 0x000E4570 File Offset: 0x000E2770
		private void Vector2PropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F52 RID: 8018 RVA: 0x000E4579 File Offset: 0x000E2779
		private void doublePropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F53 RID: 8019 RVA: 0x000E4582 File Offset: 0x000E2782
		private void intPropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F54 RID: 8020 RVA: 0x000E458B File Offset: 0x000E278B
		private void uintPropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F55 RID: 8021 RVA: 0x000E4594 File Offset: 0x000E2794
		private void ColorPropertyChangedListenerOf_widget_0_3_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_0_0(propertyName);
		}

		// Token: 0x06001F56 RID: 8022 RVA: 0x000E45A0 File Offset: 0x000E27A0
		private void HandleWidgetPropertyChangeOf_widget_0_3_0_0(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._datasource_Root_ShortcutKey.KeyID = this._widget_0_3_0_0.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_ShortcutKey.IsVisible = this._widget_0_3_0_0.IsVisible;
				return;
			}
		}

		// Token: 0x06001F57 RID: 8023 RVA: 0x000E45F5 File Offset: 0x000E27F5
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F58 RID: 8024 RVA: 0x000E4603 File Offset: 0x000E2803
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F59 RID: 8025 RVA: 0x000E4612 File Offset: 0x000E2812
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F5A RID: 8026 RVA: 0x000E4621 File Offset: 0x000E2821
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F5B RID: 8027 RVA: 0x000E4630 File Offset: 0x000E2830
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F5C RID: 8028 RVA: 0x000E463F File Offset: 0x000E283F
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F5D RID: 8029 RVA: 0x000E464E File Offset: 0x000E284E
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F5E RID: 8030 RVA: 0x000E465D File Offset: 0x000E285D
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F5F RID: 8031 RVA: 0x000E466C File Offset: 0x000E286C
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001F60 RID: 8032 RVA: 0x000E467C File Offset: 0x000E287C
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Quests")
			{
				this.RefreshDataSource_datasource_Root_Quests(this._datasource_Root.Quests);
				return;
			}
			if (propertyName == "ShortcutKey")
			{
				this.RefreshDataSource_datasource_Root_ShortcutKey(this._datasource_Root.ShortcutKey);
				return;
			}
			if (propertyName == "ItemHint")
			{
				this.RefreshDataSource_datasource_Root_ItemHint(this._datasource_Root.ItemHint);
				return;
			}
			if (propertyName == "IsWaitActive")
			{
				this._widget.IsWaitActive = this._datasource_Root.IsWaitActive;
				return;
			}
			if (propertyName == "ItemType")
			{
				this._widget.ItemType = this._datasource_Root.ItemType;
				return;
			}
			if (propertyName == "OptionLeaveType")
			{
				this._widget.LeaveType = this._datasource_Root.OptionLeaveType;
				return;
			}
			if (propertyName == "GameMenuStringId")
			{
				this._widget.GameMenuStringId = this._datasource_Root.GameMenuStringId;
				return;
			}
			if (propertyName == "BattleSize")
			{
				this._widget.BattleSize = this._datasource_Root.BattleSize;
				return;
			}
			if (propertyName == "IsNavalBattle")
			{
				this._widget.IsNavalBattle = this._datasource_Root.IsNavalBattle;
				return;
			}
			if (propertyName == "IsEnabled")
			{
				this._widget_0.IsEnabled = this._datasource_Root.IsEnabled;
				this._widget_0_3.IsEnabled = this._datasource_Root.IsEnabled;
				this._widget_0_3_0.IsVisible = this._datasource_Root.IsEnabled;
				return;
			}
			if (propertyName == "IsHighlightEnabled")
			{
				this._widget_0_2.IsHighlightEnabled = this._datasource_Root.IsHighlightEnabled;
				return;
			}
			if (propertyName == "Item")
			{
				this._widget_0_3.Text = this._datasource_Root.Item;
				return;
			}
		}

		// Token: 0x06001F61 RID: 8033 RVA: 0x000E4856 File Offset: 0x000E2A56
		private void ViewModelPropertyChangedListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F62 RID: 8034 RVA: 0x000E4864 File Offset: 0x000E2A64
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F63 RID: 8035 RVA: 0x000E4873 File Offset: 0x000E2A73
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F64 RID: 8036 RVA: 0x000E4882 File Offset: 0x000E2A82
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F65 RID: 8037 RVA: 0x000E4891 File Offset: 0x000E2A91
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F66 RID: 8038 RVA: 0x000E48A0 File Offset: 0x000E2AA0
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F67 RID: 8039 RVA: 0x000E48AF File Offset: 0x000E2AAF
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F68 RID: 8040 RVA: 0x000E48BE File Offset: 0x000E2ABE
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F69 RID: 8041 RVA: 0x000E48CD File Offset: 0x000E2ACD
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ShortcutKey(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(e.PropertyName);
		}

		// Token: 0x06001F6A RID: 8042 RVA: 0x000E48DC File Offset: 0x000E2ADC
		private void HandleViewModelPropertyChangeOf_datasource_Root_ShortcutKey(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._widget_0_3_0_0.KeyID = this._datasource_Root_ShortcutKey.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._widget_0_3_0_0.IsVisible = this._datasource_Root_ShortcutKey.IsVisible;
				return;
			}
		}

		// Token: 0x06001F6B RID: 8043 RVA: 0x000E4931 File Offset: 0x000E2B31
		private void ViewModelPropertyChangedListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F6C RID: 8044 RVA: 0x000E493F File Offset: 0x000E2B3F
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F6D RID: 8045 RVA: 0x000E494E File Offset: 0x000E2B4E
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F6E RID: 8046 RVA: 0x000E495D File Offset: 0x000E2B5D
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F6F RID: 8047 RVA: 0x000E496C File Offset: 0x000E2B6C
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F70 RID: 8048 RVA: 0x000E497B File Offset: 0x000E2B7B
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F71 RID: 8049 RVA: 0x000E498A File Offset: 0x000E2B8A
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F72 RID: 8050 RVA: 0x000E4999 File Offset: 0x000E2B99
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F73 RID: 8051 RVA: 0x000E49A8 File Offset: 0x000E2BA8
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ItemHint(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(e.PropertyName);
		}

		// Token: 0x06001F74 RID: 8052 RVA: 0x000E49B7 File Offset: 0x000E2BB7
		private void HandleViewModelPropertyChangeOf_datasource_Root_ItemHint(string propertyName)
		{
		}

		// Token: 0x06001F75 RID: 8053 RVA: 0x000E49BC File Offset: 0x000E2BBC
		public void OnList_datasource_Root_QuestsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_1.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_Quests.Count; j++)
				{
					QuestMarkerVM bindingObject = this._datasource_Root_Quests[j];
					this._widget_0_1.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate);
				QuestMarkerVM questMarkerVM = this._datasource_Root_Quests[e.NewIndex];
				generatedWidgetData.Data = questMarkerVM;
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_1.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate, e.NewIndex);
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.CreateWidgets();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetIds();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetAttributes();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetDataSource(questMarkerVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_1.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_1.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_1.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06001F76 RID: 8054 RVA: 0x000E4B58 File Offset: 0x000E2D58
		private void RefreshDataSource_datasource_Root(GameMenuItemVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_2;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3_0;
				if (this._datasource_Root_Quests != null)
				{
					this._datasource_Root_Quests.ListChanged -= this.OnList_datasource_Root_QuestsChanged;
					for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_1.GetChild(i);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_1.GetChild(i);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_1.RemoveChild(child2);
					}
					this._datasource_Root_Quests = null;
				}
				if (this._datasource_Root_ShortcutKey != null)
				{
					this._datasource_Root_ShortcutKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ShortcutKey;
					this._widget_0_3_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3_0_0;
					this._datasource_Root_ShortcutKey = null;
				}
				if (this._datasource_Root_ItemHint != null)
				{
					this._datasource_Root_ItemHint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ItemHint;
					this._widget_0_4.EventFire -= this.EventListenerOf_widget_0_4;
					this._widget_1.EventFire -= this.EventListenerOf_widget_1;
					this._datasource_Root_ItemHint = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.IsWaitActive = this._datasource_Root.IsWaitActive;
				this._widget.ItemType = this._datasource_Root.ItemType;
				this._widget.LeaveType = this._datasource_Root.OptionLeaveType;
				this._widget.GameMenuStringId = this._datasource_Root.GameMenuStringId;
				this._widget.BattleSize = this._datasource_Root.BattleSize;
				this._widget.IsNavalBattle = this._datasource_Root.IsNavalBattle;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.IsEnabled = this._datasource_Root.IsEnabled;
				this._widget_0.EventFire += this.EventListenerOf_widget_0;
				this._widget_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_0_2.IsHighlightEnabled = this._datasource_Root.IsHighlightEnabled;
				this._widget_0_2.PropertyChanged += this.PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_2;
				this._widget_0_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_2;
				this._widget_0_3.IsEnabled = this._datasource_Root.IsEnabled;
				this._widget_0_3.Text = this._datasource_Root.Item;
				this._widget_0_3.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3_0.IsVisible = this._datasource_Root.IsEnabled;
				this._widget_0_3_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3_0;
				this._widget_0_3_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3_0;
				this._datasource_Root_Quests = this._datasource_Root.Quests;
				if (this._datasource_Root_Quests != null)
				{
					this._datasource_Root_Quests.ListChanged += this.OnList_datasource_Root_QuestsChanged;
					for (int j = 0; j < this._datasource_Root_Quests.Count; j++)
					{
						GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate);
						QuestMarkerVM questMarkerVM = this._datasource_Root_Quests[j];
						generatedWidgetData.Data = questMarkerVM;
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_1.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate, j);
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.CreateWidgets();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetIds();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetAttributes();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetDataSource(questMarkerVM);
					}
				}
				this._datasource_Root_ShortcutKey = this._datasource_Root.ShortcutKey;
				if (this._datasource_Root_ShortcutKey != null)
				{
					this._datasource_Root_ShortcutKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ShortcutKey;
					this._datasource_Root_ShortcutKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ShortcutKey;
					this._widget_0_3_0_0.KeyID = this._datasource_Root_ShortcutKey.KeyID;
					this._widget_0_3_0_0.IsVisible = this._datasource_Root_ShortcutKey.IsVisible;
					this._widget_0_3_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3_0_0;
					this._widget_0_3_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3_0_0;
				}
				this._datasource_Root_ItemHint = this._datasource_Root.ItemHint;
				if (this._datasource_Root_ItemHint != null)
				{
					this._datasource_Root_ItemHint.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ItemHint;
					this._datasource_Root_ItemHint.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ItemHint;
					this._widget_0_4.EventFire += this.EventListenerOf_widget_0_4;
					this._widget_1.EventFire += this.EventListenerOf_widget_1;
				}
			}
		}

		// Token: 0x06001F77 RID: 8055 RVA: 0x000E5D44 File Offset: 0x000E3F44
		private void RefreshDataSource_datasource_Root_Quests(MBBindingList<QuestMarkerVM> newDataSource)
		{
			if (this._datasource_Root_Quests != null)
			{
				this._datasource_Root_Quests.ListChanged -= this.OnList_datasource_Root_QuestsChanged;
				for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_1.RemoveChild(child2);
				}
				this._datasource_Root_Quests = null;
			}
			this._datasource_Root_Quests = newDataSource;
			this._datasource_Root_Quests = this._datasource_Root.Quests;
			if (this._datasource_Root_Quests != null)
			{
				this._datasource_Root_Quests.ListChanged += this.OnList_datasource_Root_QuestsChanged;
				for (int j = 0; j < this._datasource_Root_Quests.Count; j++)
				{
					GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate);
					QuestMarkerVM questMarkerVM = this._datasource_Root_Quests[j];
					generatedWidgetData.Data = questMarkerVM;
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_1.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate, j);
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.CreateWidgets();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetIds();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetAttributes();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_5_ItemTemplate.SetDataSource(questMarkerVM);
				}
			}
		}

		// Token: 0x06001F78 RID: 8056 RVA: 0x000E5E80 File Offset: 0x000E4080
		private void RefreshDataSource_datasource_Root_ShortcutKey(InputKeyItemVM newDataSource)
		{
			if (this._datasource_Root_ShortcutKey != null)
			{
				this._datasource_Root_ShortcutKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ShortcutKey;
				this._widget_0_3_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3_0_0;
				this._datasource_Root_ShortcutKey = null;
			}
			this._datasource_Root_ShortcutKey = newDataSource;
			this._datasource_Root_ShortcutKey = this._datasource_Root.ShortcutKey;
			if (this._datasource_Root_ShortcutKey != null)
			{
				this._datasource_Root_ShortcutKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ShortcutKey;
				this._datasource_Root_ShortcutKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ShortcutKey;
				this._widget_0_3_0_0.KeyID = this._datasource_Root_ShortcutKey.KeyID;
				this._widget_0_3_0_0.IsVisible = this._datasource_Root_ShortcutKey.IsVisible;
				this._widget_0_3_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3_0_0;
				this._widget_0_3_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3_0_0;
			}
		}

		// Token: 0x06001F79 RID: 8057 RVA: 0x000E622C File Offset: 0x000E442C
		private void RefreshDataSource_datasource_Root_ItemHint(HintViewModel newDataSource)
		{
			if (this._datasource_Root_ItemHint != null)
			{
				this._datasource_Root_ItemHint.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ItemHint;
				this._widget_0_4.EventFire -= this.EventListenerOf_widget_0_4;
				this._widget_1.EventFire -= this.EventListenerOf_widget_1;
				this._datasource_Root_ItemHint = null;
			}
			this._datasource_Root_ItemHint = newDataSource;
			this._datasource_Root_ItemHint = this._datasource_Root.ItemHint;
			if (this._datasource_Root_ItemHint != null)
			{
				this._datasource_Root_ItemHint.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ItemHint;
				this._datasource_Root_ItemHint.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ItemHint;
				this._widget_0_4.EventFire += this.EventListenerOf_widget_0_4;
				this._widget_1.EventFire += this.EventListenerOf_widget_1;
			}
		}

		// Token: 0x04000690 RID: 1680
		private GameMenuItemWidget _widget;

		// Token: 0x04000691 RID: 1681
		private ButtonWidget _widget_0;

		// Token: 0x04000692 RID: 1682
		private ImageWidget _widget_0_0;

		// Token: 0x04000693 RID: 1683
		private ListPanel _widget_0_1;

		// Token: 0x04000694 RID: 1684
		private TutorialHighlightItemBrushWidget _widget_0_2;

		// Token: 0x04000695 RID: 1685
		private RichTextWidget _widget_0_3;

		// Token: 0x04000696 RID: 1686
		private Widget _widget_0_3_0;

		// Token: 0x04000697 RID: 1687
		private InputKeyVisualWidget _widget_0_3_0_0;

		// Token: 0x04000698 RID: 1688
		private HintWidget _widget_0_4;

		// Token: 0x04000699 RID: 1689
		private Widget _widget_0_5;

		// Token: 0x0400069A RID: 1690
		private HintWidget _widget_1;

		// Token: 0x0400069B RID: 1691
		private GameMenuItemVM _datasource_Root;

		// Token: 0x0400069C RID: 1692
		private MBBindingList<QuestMarkerVM> _datasource_Root_Quests;

		// Token: 0x0400069D RID: 1693
		private InputKeyItemVM _datasource_Root_ShortcutKey;

		// Token: 0x0400069E RID: 1694
		private HintViewModel _datasource_Root_ItemHint;
	}
}
