using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000361 RID: 865
	public class GangLeaderNeedsRecruitsIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x06003361 RID: 13153 RVA: 0x000D3E18 File Offset: 0x000D2018
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06003362 RID: 13154 RVA: 0x000D3E31 File Offset: 0x000D2031
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x06003363 RID: 13155 RVA: 0x000D3E33 File Offset: 0x000D2033
		private static bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.CurrentSettlement != null && issueGiver.IsGangLeader;
		}

		// Token: 0x06003364 RID: 13156 RVA: 0x000D3E48 File Offset: 0x000D2048
		public void OnCheckForIssue(Hero hero)
		{
			if (GangLeaderNeedsRecruitsIssueBehavior.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(GangLeaderNeedsRecruitsIssueBehavior.OnSelected), typeof(GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x06003365 RID: 13157 RVA: 0x000D3EAB File Offset: 0x000D20AB
		private static IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssue(issueOwner);
		}

		// Token: 0x04000EBA RID: 3770
		private const IssueBase.IssueFrequency GangLeaderNeedsRecruitsIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000705 RID: 1797
		public class GangLeaderNeedsRecruitsIssue : IssueBase
		{
			// Token: 0x06005735 RID: 22325 RVA: 0x0019AE1A File Offset: 0x0019901A
			internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsRecruitsIssue(object o, List<object> collectedObjects)
			{
				((GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005736 RID: 22326 RVA: 0x0019AE28 File Offset: 0x00199028
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x1700109E RID: 4254
			// (get) Token: 0x06005737 RID: 22327 RVA: 0x0019AE31 File Offset: 0x00199031
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.RequiredTroops;
				}
			}

			// Token: 0x1700109F RID: 4255
			// (get) Token: 0x06005738 RID: 22328 RVA: 0x0019AE34 File Offset: 0x00199034
			private int RequestedRecruitCount
			{
				get
				{
					return 6 + MathF.Ceiling(10f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170010A0 RID: 4256
			// (get) Token: 0x06005739 RID: 22329 RVA: 0x0019AE49 File Offset: 0x00199049
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 11 + MathF.Ceiling(9f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170010A1 RID: 4257
			// (get) Token: 0x0600573A RID: 22330 RVA: 0x0019AE5F File Offset: 0x0019905F
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 6 + MathF.Ceiling(7f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x170010A2 RID: 4258
			// (get) Token: 0x0600573B RID: 22331 RVA: 0x0019AE74 File Offset: 0x00199074
			protected override int RewardGold
			{
				get
				{
					return 2000 + this.RequestedRecruitCount * 100;
				}
			}

			// Token: 0x170010A3 RID: 4259
			// (get) Token: 0x0600573C RID: 22332 RVA: 0x0019AE85 File Offset: 0x00199085
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=YxtiyxSf}Yes... As you no doubt know, this is rough work, and I've lost a lot of good lads recently. I haven't had much luck replacing them. I need men who understand how things work in our business, and that's not always easy to find. I could use bandits and looters. They usually know their stuff. But if I take them in as prisoners, they'll just slip away as soon as I get the chance. I need volunteers...[ib:hip][if:convo_undecided_closed]", null);
				}
			}

			// Token: 0x170010A4 RID: 4260
			// (get) Token: 0x0600573D RID: 22333 RVA: 0x0019AE92 File Offset: 0x00199092
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=jGpBZDvC}I see. What do you want from me?", null);
				}
			}

			// Token: 0x170010A5 RID: 4261
			// (get) Token: 0x0600573E RID: 22334 RVA: 0x0019AE9F File Offset: 0x0019909F
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					return new TextObject("{=Qh26ReAv}Look, I know that warriors like you can sometimes recruit bandits to your party. Some of those men might want to take their chances working for me. More comfortable in living in town, where there's always drink and women on hand, then roaming endlessly about the countryside, eh? For each one that signs up with me I'll give you a bounty, more if they have some experience.[if:convo_innocent_smile][ib:hip]", null);
				}
			}

			// Token: 0x170010A6 RID: 4262
			// (get) Token: 0x0600573F RID: 22335 RVA: 0x0019AEAC File Offset: 0x001990AC
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=ekLDmgS7}I'll find your recruits.", null);
				}
			}

			// Token: 0x170010A7 RID: 4263
			// (get) Token: 0x06005740 RID: 22336 RVA: 0x0019AEB9 File Offset: 0x001990B9
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					return new TextObject("{=bKfaMFVK}You can also send me a recruiter: a trustworthy companion who is good at leading men, and also enough of a rogue to win the trust of other rogues...[if:convo_undecided_open][ib:confident]", null);
				}
			}

			// Token: 0x170010A8 RID: 4264
			// (get) Token: 0x06005741 RID: 22337 RVA: 0x0019AEC6 File Offset: 0x001990C6
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=kxvnA811}All right, I will send you someone from my party who fits your bill.", null);
				}
			}

			// Token: 0x170010A9 RID: 4265
			// (get) Token: 0x06005742 RID: 22338 RVA: 0x0019AED3 File Offset: 0x001990D3
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=8sDjwsnW}I'm sure your lieutenant will solve my problem. Thank you for your help.[if:convo_nonchalant][ib:demure2]", null);
				}
			}

			// Token: 0x170010AA RID: 4266
			// (get) Token: 0x06005743 RID: 22339 RVA: 0x0019AEE0 File Offset: 0x001990E0
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=TkvsBd4H}Your companion seems to have a knack with the local never-do-wells. I hear a lot of fine lads have already signed up.[if:convo_relaxed_happy][ib:hip2]", null);
				}
			}

			// Token: 0x170010AB RID: 4267
			// (get) Token: 0x06005744 RID: 22340 RVA: 0x0019AEED File Offset: 0x001990ED
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x170010AC RID: 4268
			// (get) Token: 0x06005745 RID: 22341 RVA: 0x0019AEF0 File Offset: 0x001990F0
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170010AD RID: 4269
			// (get) Token: 0x06005746 RID: 22342 RVA: 0x0019AEF4 File Offset: 0x001990F4
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=wX14wxqF}You asked {COMPANION.LINK} to deliver at least {WANTED_RECRUIT_AMOUNT} looters and bandits to {ISSUE_GIVER.LINK} in {SETTLEMENT}. They should rejoin your party in {RETURN_DAYS} days.", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					textObject.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, false);
					textObject.SetTextVariable("WANTED_RECRUIT_AMOUNT", this.RequestedRecruitCount);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x170010AE RID: 4270
			// (get) Token: 0x06005747 RID: 22343 RVA: 0x0019AF7A File Offset: 0x0019917A
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=rrh7rSLs}Gang Needs Recruits", null);
				}
			}

			// Token: 0x170010AF RID: 4271
			// (get) Token: 0x06005748 RID: 22344 RVA: 0x0019AF87 File Offset: 0x00199187
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=0kYaAb7c}A gang leader needs recruits for {?ISSUE_GIVER.GENDER}her{?}his{\\?} gang.", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x06005749 RID: 22345 RVA: 0x0019AFAB File Offset: 0x001991AB
			public GangLeaderNeedsRecruitsIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
			}

			// Token: 0x0600574A RID: 22346 RVA: 0x0019AFBE File Offset: 0x001991BE
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x0600574B RID: 22347 RVA: 0x0019AFD3 File Offset: 0x001991D3
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Leadership) >= hero.GetSkillValue(DefaultSkills.Roguery)) ? DefaultSkills.Leadership : DefaultSkills.Roguery, 120);
			}

			// Token: 0x0600574C RID: 22348 RVA: 0x0019B000 File Offset: 0x00199200
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x0600574D RID: 22349 RVA: 0x0019B011 File Offset: 0x00199211
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x0600574E RID: 22350 RVA: 0x0019B02B File Offset: 0x0019922B
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x0600574F RID: 22351 RVA: 0x0019B039 File Offset: 0x00199239
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005750 RID: 22352 RVA: 0x0019B03B File Offset: 0x0019923B
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005751 RID: 22353 RVA: 0x0019B03D File Offset: 0x0019923D
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this.RequestedRecruitCount);
			}

			// Token: 0x06005752 RID: 22354 RVA: 0x0019B05B File Offset: 0x0019925B
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005753 RID: 22355 RVA: 0x0019B05E File Offset: 0x0019925E
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flag = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005754 RID: 22356 RVA: 0x0019B089 File Offset: 0x00199289
			public override bool IssueStayAliveConditions()
			{
				return true;
			}

			// Token: 0x06005755 RID: 22357 RVA: 0x0019B08C File Offset: 0x0019928C
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x170010B0 RID: 4272
			// (get) Token: 0x06005756 RID: 22358 RVA: 0x0019B08E File Offset: 0x0019928E
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06005757 RID: 22359 RVA: 0x0019B0A3 File Offset: 0x001992A3
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.IssueOwner.AddPower(10f);
				this.RelationshipChangeWithIssueOwner = 5;
			}

			// Token: 0x04001C8D RID: 7309
			private const int IssueAndQuestDuration = 30;

			// Token: 0x04001C8E RID: 7310
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x04001C8F RID: 7311
			private const int AlternativeSolutionRelationBonus = 5;

			// Token: 0x04001C90 RID: 7312
			private const int AlternativeSolutionNotablePowerBonus = 10;

			// Token: 0x04001C91 RID: 7313
			private const int AlternativeSolutionPlayerHonorBonus = 30;

			// Token: 0x04001C92 RID: 7314
			private const int AlternativeSolutionRewardPerRecruit = 100;

			// Token: 0x04001C93 RID: 7315
			private const int CompanionRequiredSkillLevel = 120;
		}

		// Token: 0x02000706 RID: 1798
		public class GangLeaderNeedsRecruitsIssueQuest : QuestBase
		{
			// Token: 0x06005758 RID: 22360 RVA: 0x0019B0DC File Offset: 0x001992DC
			internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsRecruitsIssueQuest(object o, List<object> collectedObjects)
			{
				((GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005759 RID: 22361 RVA: 0x0019B0EA File Offset: 0x001992EA
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._questProgressLogTest);
			}

			// Token: 0x0600575A RID: 22362 RVA: 0x0019B0FF File Offset: 0x001992FF
			internal static object AutoGeneratedGetMemberValue_requestedRecruitCount(object o)
			{
				return ((GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest)o)._requestedRecruitCount;
			}

			// Token: 0x0600575B RID: 22363 RVA: 0x0019B111 File Offset: 0x00199311
			internal static object AutoGeneratedGetMemberValue_deliveredRecruitCount(object o)
			{
				return ((GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest)o)._deliveredRecruitCount;
			}

			// Token: 0x0600575C RID: 22364 RVA: 0x0019B123 File Offset: 0x00199323
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest)o)._rewardGold;
			}

			// Token: 0x0600575D RID: 22365 RVA: 0x0019B135 File Offset: 0x00199335
			internal static object AutoGeneratedGetMemberValue_playerReachedRequestedAmount(object o)
			{
				return ((GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest)o)._playerReachedRequestedAmount;
			}

			// Token: 0x0600575E RID: 22366 RVA: 0x0019B147 File Offset: 0x00199347
			internal static object AutoGeneratedGetMemberValue_questProgressLogTest(object o)
			{
				return ((GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest)o)._questProgressLogTest;
			}

			// Token: 0x170010B1 RID: 4273
			// (get) Token: 0x0600575F RID: 22367 RVA: 0x0019B154 File Offset: 0x00199354
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=rrh7rSLs}Gang Needs Recruits", null);
				}
			}

			// Token: 0x170010B2 RID: 4274
			// (get) Token: 0x06005760 RID: 22368 RVA: 0x0019B161 File Offset: 0x00199361
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x170010B3 RID: 4275
			// (get) Token: 0x06005761 RID: 22369 RVA: 0x0019B164 File Offset: 0x00199364
			private TextObject QuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=PZI9Smv3}{QUEST_GIVER.LINK}, a gang leader in {SETTLEMENT}, told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs recruits for {?QUEST_GIVER.GENDER}her{?}his{\\?} gang. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to recruit {NEEDED_RECRUIT_AMOUNT} looters or bandits into your party, then transfer them to {?QUEST_GIVER.GENDER}her{?}him{\\?}. You will be paid for the recruits depending on their experience.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("NEEDED_RECRUIT_AMOUNT", this._requestedRecruitCount);
					return textObject;
				}
			}

			// Token: 0x170010B4 RID: 4276
			// (get) Token: 0x06005762 RID: 22370 RVA: 0x0019B1C1 File Offset: 0x001993C1
			private TextObject QuestSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=3ApJ6LaX}You have transferred the recruits to {QUEST_GIVER.LINK} as promised.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x170010B5 RID: 4277
			// (get) Token: 0x06005763 RID: 22371 RVA: 0x0019B1E5 File Offset: 0x001993E5
			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=iUmWTmQz}You have failed to deliver enough recruits in time. {QUEST_GIVER.LINK} must be disappointed.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x06005764 RID: 22372 RVA: 0x0019B209 File Offset: 0x00199409
			public GangLeaderNeedsRecruitsIssueQuest(string questId, Hero questGiver, CampaignTime duration, int requestedRecruitCount)
				: base(questId, questGiver, duration, 0)
			{
				this._requestedRecruitCount = requestedRecruitCount;
				this._deliveredRecruitCount = 0;
				this._rewardGold = 2000;
				this._playerReachedRequestedAmount = false;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005765 RID: 22373 RVA: 0x0019B244 File Offset: 0x00199444
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddTrackedObject(base.QuestGiver.CurrentSettlement);
				this._questProgressLogTest = base.AddDiscreteLog(this.QuestStartedLogText, new TextObject("{=r8rwl9ZS}Delivered Recruits", null), this._deliveredRecruitCount, this._requestedRecruitCount, null, false);
			}

			// Token: 0x06005766 RID: 22374 RVA: 0x0019B294 File Offset: 0x00199494
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=0QuAZ8YO}I'll be waiting. Good luck.[if:convo_relaxed_happy][ib:confident]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == this.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				TextObject npcDiscussLine = new TextObject("{=!}{GANG_LEADER_NEEDS_RECRUITS_QUEST_NOTABLE_DISCUSS}", null);
				TextObject npcResponseLine = new TextObject("{=!}{GANG_LEADER_NEEDS_RECRUITS_QUEST_NOTABLE_RESPONSE}", null);
				bool changeDialogAfterTransfer = false;
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).BeginNpcOptions(null, false).NpcOption(new TextObject("{=BGgDjRcW}I think that's enough. Here is your payment.", null), () => Hero.OneToOneConversationHero == this.QuestGiver && this._playerReachedRequestedAmount, null, null, null, null)
					.Consequence(delegate
					{
						this.ApplyQuestSuccessConsequences();
						this.CompleteQuestWithSuccess();
					})
					.CloseDialog()
					.NpcOption(npcDiscussLine, delegate
					{
						if (Hero.OneToOneConversationHero != this.QuestGiver)
						{
							return false;
						}
						if (!changeDialogAfterTransfer)
						{
							npcDiscussLine.SetTextVariable("GANG_LEADER_NEEDS_RECRUITS_QUEST_NOTABLE_DISCUSS", new TextObject("{=1hpeeCJD}Have you found any good men?[ib:confident3]", null));
							changeDialogAfterTransfer = true;
						}
						else
						{
							npcDiscussLine.SetTextVariable("GANG_LEADER_NEEDS_RECRUITS_QUEST_NOTABLE_DISCUSS", new TextObject("{=ds294zxi}Anything else?", null));
							changeDialogAfterTransfer = false;
						}
						return true;
					}, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=QbaOoilS}Yes, I have brought you a few men.", null), null, null, null)
					.Condition(() => (this.CheckIfThereIsSuitableRecruitInPlayer() && !this._playerReachedRequestedAmount) & changeDialogAfterTransfer)
					.NpcLine(npcResponseLine, null, null, null, null)
					.Condition(delegate
					{
						if (this._playerReachedRequestedAmount)
						{
							return false;
						}
						npcResponseLine.SetTextVariable("GANG_LEADER_NEEDS_RECRUITS_QUEST_NOTABLE_RESPONSE", new TextObject("{=70LnOZzo}Very good. Keep searching. We still need more men.[ib:hip2]", null));
						return true;
					})
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.OpenRecruitDeliveryScreen))
					.PlayerLine(new TextObject("{=IULW8h03}Sure.", null), null, null, null)
					.Consequence(delegate
					{
						if (this._playerReachedRequestedAmount && Campaign.Current.ConversationManager.IsConversationInProgress)
						{
							Campaign.Current.ConversationManager.ContinueConversation();
						}
					})
					.GotoDialogState("quest_discuss")
					.PlayerOption(new TextObject("{=PZqGagXt}No, not yet. I'm still looking for them.", null), null, null, null)
					.Condition(() => !this._playerReachedRequestedAmount & changeDialogAfterTransfer)
					.Consequence(delegate
					{
						changeDialogAfterTransfer = false;
					})
					.NpcLine(new TextObject("{=L1JyetPq}I am glad to hear that.[ib:closed2]", null), null, null, null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=OlOhuO7X}No thank you. Good day to you.", null), null, null, null)
					.Condition(() => !this._playerReachedRequestedAmount && !changeDialogAfterTransfer)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog()
					.EndNpcOptions();
			}

			// Token: 0x06005767 RID: 22375 RVA: 0x0019B4A0 File Offset: 0x001996A0
			private void OpenRecruitDeliveryScreen()
			{
				PartyScreenHelper.OpenScreenWithCondition(new IsTroopTransferableDelegate(this.IsTroopTransferable), new PartyPresentationDoneButtonConditionDelegate(this.DoneButtonCondition), new PartyPresentationDoneButtonDelegate(this.DoneClicked), null, PartyScreenLogic.TransferState.Transferable, PartyScreenLogic.TransferState.NotTransferable, base.QuestGiver.Name, this._requestedRecruitCount - this._deliveredRecruitCount, false, false, PartyScreenHelper.PartyScreenMode.TroopsManage, null, null);
			}

			// Token: 0x06005768 RID: 22376 RVA: 0x0019B4F8 File Offset: 0x001996F8
			private Tuple<bool, TextObject> DoneButtonCondition(TroopRoster leftMemberRoster, TroopRoster leftPrisonRoster, TroopRoster rightMemberRoster, TroopRoster rightPrisonRoster, int leftLimitNum, int rightLimitNum)
			{
				if (this._requestedRecruitCount - this._deliveredRecruitCount < leftMemberRoster.TotalManCount)
				{
					int num = this._requestedRecruitCount - this._deliveredRecruitCount;
					TextObject textObject = new TextObject("{=VOr3uoRZ}You can only transfer {X} recruit{?IS_PLURAL}s{?}{\\?}.", null);
					textObject.SetTextVariable("IS_PLURAL", (num > 1) ? 1 : 0);
					textObject.SetTextVariable("X", num);
					return new Tuple<bool, TextObject>(false, textObject);
				}
				return new Tuple<bool, TextObject>(true, null);
			}

			// Token: 0x06005769 RID: 22377 RVA: 0x0019B564 File Offset: 0x00199764
			private bool DoneClicked(TroopRoster leftMemberRoster, TroopRoster leftPrisonRoster, TroopRoster rightMemberRoster, TroopRoster rightPrisonRoster, FlattenedTroopRoster takenPrisonerRoster, FlattenedTroopRoster releasedPrisonerRoster, bool isForced, PartyBase leftParty, PartyBase rightParty)
			{
				foreach (TroopRosterElement troopRosterElement in leftMemberRoster.GetTroopRoster())
				{
					this._rewardGold += this.RewardForEachRecruit(troopRosterElement.Character) * troopRosterElement.Number;
					this._deliveredRecruitCount += troopRosterElement.Number;
				}
				this._questProgressLogTest.UpdateCurrentProgress(this._deliveredRecruitCount);
				this._questProgressLogTest.TaskName.SetTextVariable("TOTAL_REWARD", this._rewardGold);
				if (this._deliveredRecruitCount == this._requestedRecruitCount)
				{
					this._playerReachedRequestedAmount = true;
					if (Campaign.Current.ConversationManager.IsConversationInProgress)
					{
						Campaign.Current.ConversationManager.ContinueConversation();
					}
				}
				return true;
			}

			// Token: 0x0600576A RID: 22378 RVA: 0x0019B648 File Offset: 0x00199848
			private int RewardForEachRecruit(CharacterObject recruit)
			{
				return (int)(100f * ((recruit.Tier <= 1) ? 1f : ((recruit.Tier <= 3) ? 1.5f : 2f)));
			}

			// Token: 0x0600576B RID: 22379 RVA: 0x0019B676 File Offset: 0x00199876
			private bool IsTroopTransferable(CharacterObject character, PartyScreenLogic.TroopType type, PartyScreenLogic.PartyRosterSide side, PartyBase leftOwnerParty)
			{
				return this._requestedRecruitCount - this._deliveredRecruitCount >= 0 && (side == PartyScreenLogic.PartyRosterSide.Left || (MobileParty.MainParty.MemberRoster.Contains(character) && character.Occupation == Occupation.Bandit));
			}

			// Token: 0x0600576C RID: 22380 RVA: 0x0019B6B0 File Offset: 0x001998B0
			private bool CheckIfThereIsSuitableRecruitInPlayer()
			{
				bool flag = false;
				using (List<TroopRosterElement>.Enumerator enumerator = MobileParty.MainParty.MemberRoster.GetTroopRoster().GetEnumerator())
				{
					while (enumerator.MoveNext())
					{
						if (enumerator.Current.Character.Occupation == Occupation.Bandit)
						{
							flag = true;
							break;
						}
					}
				}
				return flag;
			}

			// Token: 0x0600576D RID: 22381 RVA: 0x0019B71C File Offset: 0x0019991C
			private void ApplyQuestSuccessConsequences()
			{
				base.AddLog(this.QuestSuccessLog, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
				base.QuestGiver.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = 5;
			}

			// Token: 0x0600576E RID: 22382 RVA: 0x0019B780 File Offset: 0x00199980
			protected override void OnBeforeTimedOut(ref bool completeWithSuccess, ref bool doNotResolveTheQuest)
			{
				if (this._deliveredRecruitCount >= this._requestedRecruitCount)
				{
					completeWithSuccess = true;
					this.ApplyQuestSuccessConsequences();
				}
			}

			// Token: 0x0600576F RID: 22383 RVA: 0x0019B799 File Offset: 0x00199999
			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
			}

			// Token: 0x06005770 RID: 22384 RVA: 0x0019B7C1 File Offset: 0x001999C1
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x06005771 RID: 22385 RVA: 0x0019B7C9 File Offset: 0x001999C9
			protected override void HourlyTick()
			{
			}

			// Token: 0x04001C94 RID: 7316
			private const int QuestGiverRelationBonusOnSuccess = 5;

			// Token: 0x04001C95 RID: 7317
			private const int QuestGiverNotablePowerBonusOnSuccess = 10;

			// Token: 0x04001C96 RID: 7318
			private const int QuestGiverRelationPenaltyOnFail = -5;

			// Token: 0x04001C97 RID: 7319
			private const int NotablePowerPenaltyOnFail = -10;

			// Token: 0x04001C98 RID: 7320
			private const int PlayerHonorBonusOnSuccess = 30;

			// Token: 0x04001C99 RID: 7321
			[SaveableField(1)]
			private int _requestedRecruitCount;

			// Token: 0x04001C9A RID: 7322
			[SaveableField(5)]
			private int _deliveredRecruitCount;

			// Token: 0x04001C9B RID: 7323
			[SaveableField(6)]
			private int _rewardGold;

			// Token: 0x04001C9C RID: 7324
			[SaveableField(9)]
			private bool _playerReachedRequestedAmount;

			// Token: 0x04001C9D RID: 7325
			[SaveableField(7)]
			private JournalLog _questProgressLogTest;
		}

		// Token: 0x02000707 RID: 1799
		public class GangLeaderNeedsRecruitsIssueBehaviorTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005772 RID: 22386 RVA: 0x0019B7CB File Offset: 0x001999CB
			public GangLeaderNeedsRecruitsIssueBehaviorTypeDefiner()
				: base(820000)
			{
			}

			// Token: 0x06005773 RID: 22387 RVA: 0x0019B7D8 File Offset: 0x001999D8
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssue), 1, null);
				base.AddClassDefinition(typeof(GangLeaderNeedsRecruitsIssueBehavior.GangLeaderNeedsRecruitsIssueQuest), 2, null);
			}
		}
	}
}
