using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;

namespace SandBox.GauntletUI.AutoGenerated0
{
	// Token: 0x02000073 RID: 115
	public class ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_47_ClanVillageItem__InheritedPrefab : Widget
	{
		// Token: 0x060021BC RID: 8636 RVA: 0x00114C36 File Offset: 0x00112E36
		public ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_47_ClanVillageItem__InheritedPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x060021BD RID: 8637 RVA: 0x00114C40 File Offset: 0x00112E40
		public virtual void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ButtonWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new ListPanel(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new Widget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_0_0_0 = new Widget(base.Context);
			this._widget_0_0_0.AddChild(this._widget_0_0_0_0);
			this._widget_0_0_1 = new TextWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_1);
		}

		// Token: 0x060021BE RID: 8638 RVA: 0x00114CFE File Offset: 0x00112EFE
		public virtual void SetIds()
		{
		}

		// Token: 0x060021BF RID: 8639 RVA: 0x00114D00 File Offset: 0x00112F00
		public virtual void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.DoNotPassEventsToChildren = true;
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.Brush = base.Context.GetBrush("Encyclopedia.NoAudioButton");
			this._widget_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_0_0_0.DoNotPassEventsToChildren = true;
			this._widget_0_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.SuggestedWidth = 70f;
			this._widget_0_0_0.SuggestedHeight = 70f;
			this._widget_0_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_0.Sprite = base.Context.SpriteData.GetSprite("Clan\\portrait_slot_right_panel");
			this._widget_0_0_0_0.DoNotPassEventsToChildren = true;
			this._widget_0_0_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_0_0.MarginLeft = 2f;
			this._widget_0_0_0_0.MarginRight = 2f;
			this._widget_0_0_0_0.MarginTop = 2f;
			this._widget_0_0_0_0.MarginBottom = 2f;
			this._widget_0_0_0_0.IsDisabled = true;
			this._widget_0_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_1.SuggestedWidth = 84f;
			this._widget_0_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1.MarginTop = 5f;
			this._widget_0_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_1.Brush = base.Context.GetBrush("Clan.Village.Name.Text");
		}

		// Token: 0x060021C0 RID: 8640 RVA: 0x00114EC4 File Offset: 0x001130C4
		public virtual void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1;
				this._datasource_Root = null;
			}
		}

		// Token: 0x060021C1 RID: 8641 RVA: 0x00115167 File Offset: 0x00113367
		public virtual void SetDataSource(ClanSettlementItemVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060021C2 RID: 8642 RVA: 0x00115170 File Offset: 0x00113370
		private void EventListenerOf_widget_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteLink();
			}
			if (commandName == "HoverBegin")
			{
				this._datasource_Root.ExecuteOpenTooltip();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root.ExecuteCloseTooltip();
			}
		}

		// Token: 0x060021C3 RID: 8643 RVA: 0x001151C5 File Offset: 0x001133C5
		private void PropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021C4 RID: 8644 RVA: 0x001151CE File Offset: 0x001133CE
		private void boolPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021C5 RID: 8645 RVA: 0x001151D7 File Offset: 0x001133D7
		private void floatPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021C6 RID: 8646 RVA: 0x001151E0 File Offset: 0x001133E0
		private void Vec2PropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021C7 RID: 8647 RVA: 0x001151E9 File Offset: 0x001133E9
		private void Vector2PropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021C8 RID: 8648 RVA: 0x001151F2 File Offset: 0x001133F2
		private void doublePropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021C9 RID: 8649 RVA: 0x001151FB File Offset: 0x001133FB
		private void intPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021CA RID: 8650 RVA: 0x00115204 File Offset: 0x00113404
		private void uintPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021CB RID: 8651 RVA: 0x0011520D File Offset: 0x0011340D
		private void ColorPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060021CC RID: 8652 RVA: 0x00115216 File Offset: 0x00113416
		private void HandleWidgetPropertyChangeOf_widget_0_0_0_0(string propertyName)
		{
			if (propertyName == "Sprite")
			{
				this._datasource_Root.FileName = this._widget_0_0_0_0.Sprite.Name;
				return;
			}
		}

		// Token: 0x060021CD RID: 8653 RVA: 0x00115241 File Offset: 0x00113441
		private void PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021CE RID: 8654 RVA: 0x0011524A File Offset: 0x0011344A
		private void boolPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021CF RID: 8655 RVA: 0x00115253 File Offset: 0x00113453
		private void floatPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021D0 RID: 8656 RVA: 0x0011525C File Offset: 0x0011345C
		private void Vec2PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021D1 RID: 8657 RVA: 0x00115265 File Offset: 0x00113465
		private void Vector2PropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021D2 RID: 8658 RVA: 0x0011526E File Offset: 0x0011346E
		private void doublePropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021D3 RID: 8659 RVA: 0x00115277 File Offset: 0x00113477
		private void intPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021D4 RID: 8660 RVA: 0x00115280 File Offset: 0x00113480
		private void uintPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021D5 RID: 8661 RVA: 0x00115289 File Offset: 0x00113489
		private void ColorPropertyChangedListenerOf_widget_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1(propertyName);
		}

		// Token: 0x060021D6 RID: 8662 RVA: 0x00115292 File Offset: 0x00113492
		private void HandleWidgetPropertyChangeOf_widget_0_0_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.Name = this._widget_0_0_1.Text;
				return;
			}
		}

		// Token: 0x060021D7 RID: 8663 RVA: 0x001152B8 File Offset: 0x001134B8
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021D8 RID: 8664 RVA: 0x001152C6 File Offset: 0x001134C6
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021D9 RID: 8665 RVA: 0x001152D5 File Offset: 0x001134D5
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021DA RID: 8666 RVA: 0x001152E4 File Offset: 0x001134E4
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021DB RID: 8667 RVA: 0x001152F3 File Offset: 0x001134F3
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021DC RID: 8668 RVA: 0x00115302 File Offset: 0x00113502
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021DD RID: 8669 RVA: 0x00115311 File Offset: 0x00113511
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021DE RID: 8670 RVA: 0x00115320 File Offset: 0x00113520
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021DF RID: 8671 RVA: 0x0011532F File Offset: 0x0011352F
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060021E0 RID: 8672 RVA: 0x00115340 File Offset: 0x00113540
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "FileName")
			{
				if (this._datasource_Root.FileName != null)
				{
					this._widget_0_0_0_0.Sprite = base.Context.SpriteData.GetSprite(this._datasource_Root.FileName);
				}
				return;
			}
			if (propertyName == "Name")
			{
				this._widget_0_0_1.Text = this._datasource_Root.Name;
				return;
			}
		}

		// Token: 0x060021E1 RID: 8673 RVA: 0x001153B4 File Offset: 0x001135B4
		private void RefreshDataSource_datasource_Root(ClanSettlementItemVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.EventFire += this.EventListenerOf_widget_0;
				if (this._datasource_Root.FileName != null)
				{
					this._widget_0_0_0_0.Sprite = base.Context.SpriteData.GetSprite(this._datasource_Root.FileName);
				}
				this._widget_0_0_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_1.Text = this._datasource_Root.Name;
				this._widget_0_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_1;
				this._widget_0_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_1;
			}
		}

		// Token: 0x0400073E RID: 1854
		private Widget _widget;

		// Token: 0x0400073F RID: 1855
		private ButtonWidget _widget_0;

		// Token: 0x04000740 RID: 1856
		private ListPanel _widget_0_0;

		// Token: 0x04000741 RID: 1857
		private Widget _widget_0_0_0;

		// Token: 0x04000742 RID: 1858
		private Widget _widget_0_0_0_0;

		// Token: 0x04000743 RID: 1859
		private TextWidget _widget_0_0_1;

		// Token: 0x04000744 RID: 1860
		private ClanSettlementItemVM _datasource_Root;
	}
}
