using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.WeaponCrafting.WeaponDesign;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Crafting;

namespace SandBox.GauntletUI.AutoGenerated0
{
	// Token: 0x0200009B RID: 155
	public class Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate : CraftedWeaponDesignResultListPanel
	{
		// Token: 0x06002EC4 RID: 11972 RVA: 0x0018176E File Offset: 0x0017F96E
		public Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06002EC5 RID: 11973 RVA: 0x00181778 File Offset: 0x0017F978
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new RichTextWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new BoolBrushChangerBrushWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new TextWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_1 = new HintWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
			this._widget_2 = new CounterTextBrushWidget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2_0 = new HintWidget(base.Context);
			this._widget_2.AddChild(this._widget_2_0);
			this._widget_3 = new Widget(base.Context);
			this._widget.AddChild(this._widget_3);
			this._widget_3_0 = new CounterTextBrushWidget(base.Context);
			this._widget_3.AddChild(this._widget_3_0);
			this._widget_3_0_0 = new HintWidget(base.Context);
			this._widget_3_0.AddChild(this._widget_3_0_0);
		}

		// Token: 0x06002EC6 RID: 11974 RVA: 0x001818C0 File Offset: 0x0017FAC0
		public void SetIds()
		{
			this._widget_0.Id = "Label";
			this._widget_2.Id = "ValueTextWidget";
			this._widget_3.Id = "ChangeValueTextParentWidget";
			this._widget_3_0.Id = "ChangeValueTextWidget";
		}

		// Token: 0x06002EC7 RID: 11975 RVA: 0x00181910 File Offset: 0x0017FB10
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedHeight = 25f;
			base.MarginTop = 4f;
			base.MarginBottom = 4f;
			base.MarginLeft = 20f;
			base.MarginRight = 8f;
			base.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			base.LabelTextWidget = this._widget_0;
			base.ValueTextWidget = this._widget_2;
			base.ChangeValueTextWidget = this._widget_3_0;
			base.GoldEffectorTextWidget = this._widget.FindChild("GoldEffectorParentWidget/GoldEffectorTextWidget") as RichTextWidget;
			base.PositiveChangeBrush = base.Context.GetBrush("Crafting.Result.Positive");
			base.NegativeChangeBrush = base.Context.GetBrush("Crafting.Result.Negative");
			base.NeutralBrush = base.Context.GetBrush("Crafting.Result.Neutral");
			base.FadeInTimeIndexOffset = 0.5f;
			base.FadeInTime = 0.5f;
			base.CounterStartTime = 0.5f;
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.Brush = base.Context.GetBrush("Crafting.Popup.Property.Name.Text");
			this._widget_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.IncludeChildren = true;
			this._widget_1.FalseBrush = "Crafting.Result.Negative";
			this._widget_1.TrueBrush = "Crafting.Result.Positive";
			this._widget_1_0.DoNotAcceptEvents = true;
			this._widget_1_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.MarginRight = 5f;
			this._widget_1_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.SuggestedWidth = 45f;
			this._widget_2.Brush = base.Context.GetBrush("Crafting.Popup.Property.Value.Text");
			this._widget_2_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_3.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.SuggestedWidth = 40f;
			this._widget_3_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_3_0.Brush = base.Context.GetBrush("Crafting.Popup.Property.Value.Text");
			this._widget_3_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
		}

		// Token: 0x06002EC8 RID: 11976 RVA: 0x00181BA4 File Offset: 0x0017FDA4
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_3_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3_0;
				if (this._datasource_Root_OrderRequirementTooltip != null)
				{
					this._datasource_Root_OrderRequirementTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._widget_1_1.EventFire -= this.EventListenerOf_widget_1_1;
					this._datasource_Root_OrderRequirementTooltip = null;
				}
				if (this._datasource_Root_CraftedValueTooltip != null)
				{
					this._datasource_Root_CraftedValueTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
					this._datasource_Root_CraftedValueTooltip = null;
				}
				if (this._datasource_Root_BonusPenaltyTooltip != null)
				{
					this._datasource_Root_BonusPenaltyTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._widget_3_0_0.EventFire -= this.EventListenerOf_widget_3_0_0;
					this._datasource_Root_BonusPenaltyTooltip = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06002EC9 RID: 11977 RVA: 0x00182454 File Offset: 0x00180654
		public void SetDataSource(WeaponDesignResultPropertyItemVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06002ECA RID: 11978 RVA: 0x0018245D File Offset: 0x0018065D
		private void EventListenerOf_widget_1_1(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_OrderRequirementTooltip.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_OrderRequirementTooltip.ExecuteEndHint();
			}
		}

		// Token: 0x06002ECB RID: 11979 RVA: 0x0018248F File Offset: 0x0018068F
		private void EventListenerOf_widget_2_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_CraftedValueTooltip.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_CraftedValueTooltip.ExecuteEndHint();
			}
		}

		// Token: 0x06002ECC RID: 11980 RVA: 0x001824C1 File Offset: 0x001806C1
		private void EventListenerOf_widget_3_0_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root_BonusPenaltyTooltip.ExecuteBeginHint();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root_BonusPenaltyTooltip.ExecuteEndHint();
			}
		}

		// Token: 0x06002ECD RID: 11981 RVA: 0x001824F3 File Offset: 0x001806F3
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ECE RID: 11982 RVA: 0x001824FC File Offset: 0x001806FC
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ECF RID: 11983 RVA: 0x00182505 File Offset: 0x00180705
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ED0 RID: 11984 RVA: 0x0018250E File Offset: 0x0018070E
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ED1 RID: 11985 RVA: 0x00182517 File Offset: 0x00180717
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ED2 RID: 11986 RVA: 0x00182520 File Offset: 0x00180720
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ED3 RID: 11987 RVA: 0x00182529 File Offset: 0x00180729
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ED4 RID: 11988 RVA: 0x00182532 File Offset: 0x00180732
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ED5 RID: 11989 RVA: 0x0018253B File Offset: 0x0018073B
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002ED6 RID: 11990 RVA: 0x00182544 File Offset: 0x00180744
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "IsOrderResult")
			{
				this._datasource_Root.IsOrderResult = this._widget.IsOrderResult;
				return;
			}
			if (propertyName == "InitValue")
			{
				this._datasource_Root.InitialValue = this._widget.InitValue;
				return;
			}
			if (propertyName == "TargetValue")
			{
				this._datasource_Root.TargetValue = this._widget.TargetValue;
				return;
			}
			if (propertyName == "ChangeAmount")
			{
				this._datasource_Root.ChangeAmount = this._widget.ChangeAmount;
				return;
			}
		}

		// Token: 0x06002ED7 RID: 11991 RVA: 0x001825E1 File Offset: 0x001807E1
		private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002ED8 RID: 11992 RVA: 0x001825EA File Offset: 0x001807EA
		private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002ED9 RID: 11993 RVA: 0x001825F3 File Offset: 0x001807F3
		private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002EDA RID: 11994 RVA: 0x001825FC File Offset: 0x001807FC
		private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002EDB RID: 11995 RVA: 0x00182605 File Offset: 0x00180805
		private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002EDC RID: 11996 RVA: 0x0018260E File Offset: 0x0018080E
		private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002EDD RID: 11997 RVA: 0x00182617 File Offset: 0x00180817
		private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002EDE RID: 11998 RVA: 0x00182620 File Offset: 0x00180820
		private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002EDF RID: 11999 RVA: 0x00182629 File Offset: 0x00180829
		private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06002EE0 RID: 12000 RVA: 0x00182632 File Offset: 0x00180832
		private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.PropertyLbl = this._widget_0.Text;
				return;
			}
		}

		// Token: 0x06002EE1 RID: 12001 RVA: 0x00182658 File Offset: 0x00180858
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE2 RID: 12002 RVA: 0x00182661 File Offset: 0x00180861
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE3 RID: 12003 RVA: 0x0018266A File Offset: 0x0018086A
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE4 RID: 12004 RVA: 0x00182673 File Offset: 0x00180873
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE5 RID: 12005 RVA: 0x0018267C File Offset: 0x0018087C
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE6 RID: 12006 RVA: 0x00182685 File Offset: 0x00180885
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE7 RID: 12007 RVA: 0x0018268E File Offset: 0x0018088E
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE8 RID: 12008 RVA: 0x00182697 File Offset: 0x00180897
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EE9 RID: 12009 RVA: 0x001826A0 File Offset: 0x001808A0
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06002EEA RID: 12010 RVA: 0x001826A9 File Offset: 0x001808A9
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "BooleanCheck")
			{
				this._datasource_Root.HasBenefit = this._widget_1.BooleanCheck;
				return;
			}
		}

		// Token: 0x06002EEB RID: 12011 RVA: 0x001826CF File Offset: 0x001808CF
		private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EEC RID: 12012 RVA: 0x001826D8 File Offset: 0x001808D8
		private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EED RID: 12013 RVA: 0x001826E1 File Offset: 0x001808E1
		private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EEE RID: 12014 RVA: 0x001826EA File Offset: 0x001808EA
		private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EEF RID: 12015 RVA: 0x001826F3 File Offset: 0x001808F3
		private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EF0 RID: 12016 RVA: 0x001826FC File Offset: 0x001808FC
		private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EF1 RID: 12017 RVA: 0x00182705 File Offset: 0x00180905
		private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EF2 RID: 12018 RVA: 0x0018270E File Offset: 0x0018090E
		private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EF3 RID: 12019 RVA: 0x00182717 File Offset: 0x00180917
		private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06002EF4 RID: 12020 RVA: 0x00182720 File Offset: 0x00180920
		private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.RequiredValueText = this._widget_1_0.Text;
				return;
			}
		}

		// Token: 0x06002EF5 RID: 12021 RVA: 0x00182746 File Offset: 0x00180946
		private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EF6 RID: 12022 RVA: 0x0018274F File Offset: 0x0018094F
		private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EF7 RID: 12023 RVA: 0x00182758 File Offset: 0x00180958
		private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EF8 RID: 12024 RVA: 0x00182761 File Offset: 0x00180961
		private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EF9 RID: 12025 RVA: 0x0018276A File Offset: 0x0018096A
		private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EFA RID: 12026 RVA: 0x00182773 File Offset: 0x00180973
		private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EFB RID: 12027 RVA: 0x0018277C File Offset: 0x0018097C
		private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EFC RID: 12028 RVA: 0x00182785 File Offset: 0x00180985
		private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EFD RID: 12029 RVA: 0x0018278E File Offset: 0x0018098E
		private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06002EFE RID: 12030 RVA: 0x00182797 File Offset: 0x00180997
		private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
		{
			if (propertyName == "ShowFloatingPoint")
			{
				this._datasource_Root.ShowFloatingPoint = this._widget_2.ShowFloatingPoint;
				return;
			}
		}

		// Token: 0x06002EFF RID: 12031 RVA: 0x001827BD File Offset: 0x001809BD
		private void PropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F00 RID: 12032 RVA: 0x001827C6 File Offset: 0x001809C6
		private void boolPropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F01 RID: 12033 RVA: 0x001827CF File Offset: 0x001809CF
		private void floatPropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F02 RID: 12034 RVA: 0x001827D8 File Offset: 0x001809D8
		private void Vec2PropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F03 RID: 12035 RVA: 0x001827E1 File Offset: 0x001809E1
		private void Vector2PropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F04 RID: 12036 RVA: 0x001827EA File Offset: 0x001809EA
		private void doublePropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F05 RID: 12037 RVA: 0x001827F3 File Offset: 0x001809F3
		private void intPropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F06 RID: 12038 RVA: 0x001827FC File Offset: 0x001809FC
		private void uintPropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F07 RID: 12039 RVA: 0x00182805 File Offset: 0x00180A05
		private void ColorPropertyChangedListenerOf_widget_3_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3_0(propertyName);
		}

		// Token: 0x06002F08 RID: 12040 RVA: 0x0018280E File Offset: 0x00180A0E
		private void HandleWidgetPropertyChangeOf_widget_3_0(string propertyName)
		{
			if (propertyName == "ShowFloatingPoint")
			{
				this._datasource_Root.ShowFloatingPoint = this._widget_3_0.ShowFloatingPoint;
				return;
			}
		}

		// Token: 0x06002F09 RID: 12041 RVA: 0x00182834 File Offset: 0x00180A34
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F0A RID: 12042 RVA: 0x00182842 File Offset: 0x00180A42
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F0B RID: 12043 RVA: 0x00182851 File Offset: 0x00180A51
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F0C RID: 12044 RVA: 0x00182860 File Offset: 0x00180A60
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F0D RID: 12045 RVA: 0x0018286F File Offset: 0x00180A6F
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F0E RID: 12046 RVA: 0x0018287E File Offset: 0x00180A7E
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F0F RID: 12047 RVA: 0x0018288D File Offset: 0x00180A8D
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F10 RID: 12048 RVA: 0x0018289C File Offset: 0x00180A9C
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F11 RID: 12049 RVA: 0x001828AB File Offset: 0x00180AAB
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002F12 RID: 12050 RVA: 0x001828BC File Offset: 0x00180ABC
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "OrderRequirementTooltip")
			{
				this.RefreshDataSource_datasource_Root_OrderRequirementTooltip(this._datasource_Root.OrderRequirementTooltip);
				return;
			}
			if (propertyName == "CraftedValueTooltip")
			{
				this.RefreshDataSource_datasource_Root_CraftedValueTooltip(this._datasource_Root.CraftedValueTooltip);
				return;
			}
			if (propertyName == "BonusPenaltyTooltip")
			{
				this.RefreshDataSource_datasource_Root_BonusPenaltyTooltip(this._datasource_Root.BonusPenaltyTooltip);
				return;
			}
			if (propertyName == "IsOrderResult")
			{
				this._widget.IsOrderResult = this._datasource_Root.IsOrderResult;
				return;
			}
			if (propertyName == "InitialValue")
			{
				this._widget.InitValue = this._datasource_Root.InitialValue;
				return;
			}
			if (propertyName == "TargetValue")
			{
				this._widget.TargetValue = this._datasource_Root.TargetValue;
				return;
			}
			if (propertyName == "ChangeAmount")
			{
				this._widget.ChangeAmount = this._datasource_Root.ChangeAmount;
				return;
			}
			if (propertyName == "PropertyLbl")
			{
				this._widget_0.Text = this._datasource_Root.PropertyLbl;
				return;
			}
			if (propertyName == "HasBenefit")
			{
				this._widget_1.BooleanCheck = this._datasource_Root.HasBenefit;
				return;
			}
			if (propertyName == "RequiredValueText")
			{
				this._widget_1_0.Text = this._datasource_Root.RequiredValueText;
				return;
			}
			if (propertyName == "ShowFloatingPoint")
			{
				this._widget_2.ShowFloatingPoint = this._datasource_Root.ShowFloatingPoint;
				this._widget_3_0.ShowFloatingPoint = this._datasource_Root.ShowFloatingPoint;
				return;
			}
		}

		// Token: 0x06002F13 RID: 12051 RVA: 0x00182A5C File Offset: 0x00180C5C
		private void ViewModelPropertyChangedListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F14 RID: 12052 RVA: 0x00182A6A File Offset: 0x00180C6A
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F15 RID: 12053 RVA: 0x00182A79 File Offset: 0x00180C79
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F16 RID: 12054 RVA: 0x00182A88 File Offset: 0x00180C88
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F17 RID: 12055 RVA: 0x00182A97 File Offset: 0x00180C97
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F18 RID: 12056 RVA: 0x00182AA6 File Offset: 0x00180CA6
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F19 RID: 12057 RVA: 0x00182AB5 File Offset: 0x00180CB5
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F1A RID: 12058 RVA: 0x00182AC4 File Offset: 0x00180CC4
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F1B RID: 12059 RVA: 0x00182AD3 File Offset: 0x00180CD3
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_OrderRequirementTooltip(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(e.PropertyName);
		}

		// Token: 0x06002F1C RID: 12060 RVA: 0x00182AE2 File Offset: 0x00180CE2
		private void HandleViewModelPropertyChangeOf_datasource_Root_OrderRequirementTooltip(string propertyName)
		{
		}

		// Token: 0x06002F1D RID: 12061 RVA: 0x00182AE4 File Offset: 0x00180CE4
		private void ViewModelPropertyChangedListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F1E RID: 12062 RVA: 0x00182AF2 File Offset: 0x00180CF2
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F1F RID: 12063 RVA: 0x00182B01 File Offset: 0x00180D01
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F20 RID: 12064 RVA: 0x00182B10 File Offset: 0x00180D10
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F21 RID: 12065 RVA: 0x00182B1F File Offset: 0x00180D1F
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F22 RID: 12066 RVA: 0x00182B2E File Offset: 0x00180D2E
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F23 RID: 12067 RVA: 0x00182B3D File Offset: 0x00180D3D
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F24 RID: 12068 RVA: 0x00182B4C File Offset: 0x00180D4C
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F25 RID: 12069 RVA: 0x00182B5B File Offset: 0x00180D5B
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CraftedValueTooltip(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(e.PropertyName);
		}

		// Token: 0x06002F26 RID: 12070 RVA: 0x00182B6A File Offset: 0x00180D6A
		private void HandleViewModelPropertyChangeOf_datasource_Root_CraftedValueTooltip(string propertyName)
		{
		}

		// Token: 0x06002F27 RID: 12071 RVA: 0x00182B6C File Offset: 0x00180D6C
		private void ViewModelPropertyChangedListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F28 RID: 12072 RVA: 0x00182B7A File Offset: 0x00180D7A
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F29 RID: 12073 RVA: 0x00182B89 File Offset: 0x00180D89
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F2A RID: 12074 RVA: 0x00182B98 File Offset: 0x00180D98
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F2B RID: 12075 RVA: 0x00182BA7 File Offset: 0x00180DA7
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F2C RID: 12076 RVA: 0x00182BB6 File Offset: 0x00180DB6
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F2D RID: 12077 RVA: 0x00182BC5 File Offset: 0x00180DC5
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F2E RID: 12078 RVA: 0x00182BD4 File Offset: 0x00180DD4
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F2F RID: 12079 RVA: 0x00182BE3 File Offset: 0x00180DE3
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_BonusPenaltyTooltip(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(e.PropertyName);
		}

		// Token: 0x06002F30 RID: 12080 RVA: 0x00182BF2 File Offset: 0x00180DF2
		private void HandleViewModelPropertyChangeOf_datasource_Root_BonusPenaltyTooltip(string propertyName)
		{
		}

		// Token: 0x06002F31 RID: 12081 RVA: 0x00182BF4 File Offset: 0x00180DF4
		private void RefreshDataSource_datasource_Root(WeaponDesignResultPropertyItemVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_3_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3_0;
				if (this._datasource_Root_OrderRequirementTooltip != null)
				{
					this._datasource_Root_OrderRequirementTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._widget_1_1.EventFire -= this.EventListenerOf_widget_1_1;
					this._datasource_Root_OrderRequirementTooltip = null;
				}
				if (this._datasource_Root_CraftedValueTooltip != null)
				{
					this._datasource_Root_CraftedValueTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
					this._datasource_Root_CraftedValueTooltip = null;
				}
				if (this._datasource_Root_BonusPenaltyTooltip != null)
				{
					this._datasource_Root_BonusPenaltyTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._widget_3_0_0.EventFire -= this.EventListenerOf_widget_3_0_0;
					this._datasource_Root_BonusPenaltyTooltip = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.IsOrderResult = this._datasource_Root.IsOrderResult;
				this._widget.InitValue = this._datasource_Root.InitialValue;
				this._widget.TargetValue = this._datasource_Root.TargetValue;
				this._widget.ChangeAmount = this._datasource_Root.ChangeAmount;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._widget_0.Text = this._datasource_Root.PropertyLbl;
				this._widget_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_1.BooleanCheck = this._datasource_Root.HasBenefit;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.Text = this._datasource_Root.RequiredValueText;
				this._widget_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.ShowFloatingPoint = this._datasource_Root.ShowFloatingPoint;
				this._widget_2.PropertyChanged += this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_3_0.ShowFloatingPoint = this._datasource_Root.ShowFloatingPoint;
				this._widget_3_0.PropertyChanged += this.PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3_0;
				this._widget_3_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3_0;
				this._datasource_Root_OrderRequirementTooltip = this._datasource_Root.OrderRequirementTooltip;
				if (this._datasource_Root_OrderRequirementTooltip != null)
				{
					this._datasource_Root_OrderRequirementTooltip.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_OrderRequirementTooltip;
					this._widget_1_1.EventFire += this.EventListenerOf_widget_1_1;
				}
				this._datasource_Root_CraftedValueTooltip = this._datasource_Root.CraftedValueTooltip;
				if (this._datasource_Root_CraftedValueTooltip != null)
				{
					this._datasource_Root_CraftedValueTooltip.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._datasource_Root_CraftedValueTooltip.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CraftedValueTooltip;
					this._widget_2_0.EventFire += this.EventListenerOf_widget_2_0;
				}
				this._datasource_Root_BonusPenaltyTooltip = this._datasource_Root.BonusPenaltyTooltip;
				if (this._datasource_Root_BonusPenaltyTooltip != null)
				{
					this._datasource_Root_BonusPenaltyTooltip.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_BonusPenaltyTooltip;
					this._widget_3_0_0.EventFire += this.EventListenerOf_widget_3_0_0;
				}
			}
		}

		// Token: 0x06002F32 RID: 12082 RVA: 0x00183E2C File Offset: 0x0018202C
		private void RefreshDataSource_datasource_Root_OrderRequirementTooltip(HintViewModel newDataSource)
		{
			if (this._datasource_Root_OrderRequirementTooltip != null)
			{
				this._datasource_Root_OrderRequirementTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._widget_1_1.EventFire -= this.EventListenerOf_widget_1_1;
				this._datasource_Root_OrderRequirementTooltip = null;
			}
			this._datasource_Root_OrderRequirementTooltip = newDataSource;
			this._datasource_Root_OrderRequirementTooltip = this._datasource_Root.OrderRequirementTooltip;
			if (this._datasource_Root_OrderRequirementTooltip != null)
			{
				this._datasource_Root_OrderRequirementTooltip.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._datasource_Root_OrderRequirementTooltip.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_OrderRequirementTooltip;
				this._widget_1_1.EventFire += this.EventListenerOf_widget_1_1;
			}
		}

		// Token: 0x06002F33 RID: 12083 RVA: 0x0018403C File Offset: 0x0018223C
		private void RefreshDataSource_datasource_Root_CraftedValueTooltip(HintViewModel newDataSource)
		{
			if (this._datasource_Root_CraftedValueTooltip != null)
			{
				this._datasource_Root_CraftedValueTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._widget_2_0.EventFire -= this.EventListenerOf_widget_2_0;
				this._datasource_Root_CraftedValueTooltip = null;
			}
			this._datasource_Root_CraftedValueTooltip = newDataSource;
			this._datasource_Root_CraftedValueTooltip = this._datasource_Root.CraftedValueTooltip;
			if (this._datasource_Root_CraftedValueTooltip != null)
			{
				this._datasource_Root_CraftedValueTooltip.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._datasource_Root_CraftedValueTooltip.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CraftedValueTooltip;
				this._widget_2_0.EventFire += this.EventListenerOf_widget_2_0;
			}
		}

		// Token: 0x06002F34 RID: 12084 RVA: 0x0018424C File Offset: 0x0018244C
		private void RefreshDataSource_datasource_Root_BonusPenaltyTooltip(HintViewModel newDataSource)
		{
			if (this._datasource_Root_BonusPenaltyTooltip != null)
			{
				this._datasource_Root_BonusPenaltyTooltip.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._widget_3_0_0.EventFire -= this.EventListenerOf_widget_3_0_0;
				this._datasource_Root_BonusPenaltyTooltip = null;
			}
			this._datasource_Root_BonusPenaltyTooltip = newDataSource;
			this._datasource_Root_BonusPenaltyTooltip = this._datasource_Root.BonusPenaltyTooltip;
			if (this._datasource_Root_BonusPenaltyTooltip != null)
			{
				this._datasource_Root_BonusPenaltyTooltip.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._datasource_Root_BonusPenaltyTooltip.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_BonusPenaltyTooltip;
				this._widget_3_0_0.EventFire += this.EventListenerOf_widget_3_0_0;
			}
		}

		// Token: 0x040009DF RID: 2527
		private CraftedWeaponDesignResultListPanel _widget;

		// Token: 0x040009E0 RID: 2528
		private RichTextWidget _widget_0;

		// Token: 0x040009E1 RID: 2529
		private BoolBrushChangerBrushWidget _widget_1;

		// Token: 0x040009E2 RID: 2530
		private TextWidget _widget_1_0;

		// Token: 0x040009E3 RID: 2531
		private HintWidget _widget_1_1;

		// Token: 0x040009E4 RID: 2532
		private CounterTextBrushWidget _widget_2;

		// Token: 0x040009E5 RID: 2533
		private HintWidget _widget_2_0;

		// Token: 0x040009E6 RID: 2534
		private Widget _widget_3;

		// Token: 0x040009E7 RID: 2535
		private CounterTextBrushWidget _widget_3_0;

		// Token: 0x040009E8 RID: 2536
		private HintWidget _widget_3_0_0;

		// Token: 0x040009E9 RID: 2537
		private WeaponDesignResultPropertyItemVM _datasource_Root;

		// Token: 0x040009EA RID: 2538
		private HintViewModel _datasource_Root_OrderRequirementTooltip;

		// Token: 0x040009EB RID: 2539
		private HintViewModel _datasource_Root_CraftedValueTooltip;

		// Token: 0x040009EC RID: 2540
		private HintViewModel _datasource_Root_BonusPenaltyTooltip;
	}
}
