using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace StoryMode
{
	// Token: 0x02000005 RID: 5
	public class CampaignStoryMode : Campaign
	{
		// Token: 0x17000004 RID: 4
		// (get) Token: 0x06000021 RID: 33 RVA: 0x0000290F File Offset: 0x00000B0F
		// (set) Token: 0x06000022 RID: 34 RVA: 0x00002917 File Offset: 0x00000B17
		[SaveableProperty(9999)]
		public StoryModeManager StoryMode { get; private set; }

		// Token: 0x06000023 RID: 35 RVA: 0x00002920 File Offset: 0x00000B20
		public CampaignStoryMode(CampaignGameMode gameMode)
			: base(gameMode)
		{
			this.StoryMode = new StoryModeManager();
		}

		// Token: 0x06000024 RID: 36 RVA: 0x00002934 File Offset: 0x00000B34
		protected override void BeforeRegisterTypes(MBObjectManager objectManager)
		{
			base.BeforeRegisterTypes(objectManager);
			objectManager.RegisterType<TrainingField>("TrainingField", "TrainingFields", 1U, true, false);
		}

		// Token: 0x06000025 RID: 37 RVA: 0x00002950 File Offset: 0x00000B50
		protected override void DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, out GameTypeLoadingStates nextState)
		{
			base.DoLoadingForGameType(gameTypeLoadingState, out nextState);
			if (gameTypeLoadingState == GameTypeLoadingStates.InitializeFirstStep && nextState != gameTypeLoadingState)
			{
				this.StoryMode.InitializeStoryModeObjects();
			}
			if (gameTypeLoadingState == GameTypeLoadingStates.LoadVisualsThirdState && nextState != gameTypeLoadingState)
			{
				Settlement settlement = Settlement.Find("tutorial_training_field");
				if (settlement != null)
				{
					IMapScene mapSceneWrapper = base.MapSceneWrapper;
					string stringId = settlement.StringId;
					CampaignVec2 position = settlement.Position;
					mapSceneWrapper.AddNewEntityToMapScene(stringId, in position);
				}
			}
			if (gameTypeLoadingState == GameTypeLoadingStates.PostInitializeFourthState)
			{
				this.OnSessionLaunched();
			}
		}

		// Token: 0x06000026 RID: 38 RVA: 0x000029B3 File Offset: 0x00000BB3
		private void OnSessionLaunched()
		{
			this.StoryMode.MainStoryLine.OnSessionLaunched();
		}

		// Token: 0x06000027 RID: 39 RVA: 0x000029C5 File Offset: 0x00000BC5
		internal static void AutoGeneratedStaticCollectObjectsCampaignStoryMode(object o, List<object> collectedObjects)
		{
			((CampaignStoryMode)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06000028 RID: 40 RVA: 0x000029D3 File Offset: 0x00000BD3
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.StoryMode);
		}

		// Token: 0x06000029 RID: 41 RVA: 0x000029E8 File Offset: 0x00000BE8
		internal static object AutoGeneratedGetMemberValueStoryMode(object o)
		{
			return ((CampaignStoryMode)o).StoryMode;
		}
	}
}
